### ISSUE TITLE
Video Source isn't working or incorrect time

### ISSUE THREAD

**Issue by kushariforyou** [yuliskov/SmartTube#2271]
Just updated to 17.23 Beta, and getting a lot of Vidoe Source isn't working or incorrect time errors. The screen goes black for a few seconds, then continues to play.

**Comment by langrisser1** [comment]
I just updated to 17.23 beta and also got this problem.
The video stopped playing with error "Video Source isn't working or incorrect time errors". I quitted and reopen the STN, play again the same video, no error and continue to play......

**Comment by ankitydv193** [comment]
I am also facing the same issue since updating to 17.23

**Comment by kushariforyou** [comment]
I got updated to 17.24 and still have this issue.

**Comment by aecarvalho** [comment]
Same issue for me, updated but still facing it, this happens especially when playing higher resolutions like 4K.

**Comment by Tweety63** [comment]
same here, updating to last version does nothing.

**Comment by Dermuh** [comment]
Same here. Firetv stick

**Comment by Siu07** [comment]
Same here on chromecast for Google TV. On both .23 and .24

**Comment by Siu07** [comment]
> Same here on chromecast for Google TV. On both .23 and .24

Resolved in the latest update. 
Cheers!

**Comment by aecarvalho** [comment]
yes, resolved for me too on build 17.26

**Comment by thoots99** [comment]
This APPEARED for me (NVIDIA Shield 2015, latest updated software version) on build 17.26 -- no problem before that, and it happens like "several times per minute" at times.  NOT fixed for me, to be sure.

**Comment by kushariforyou** [comment]
> 

Did you try the suggested fix in the update notes? You have to go into the developer settings and change a setting.

**Comment by thoots99** [comment]
Sorry, but I'm clueless about any of that.  Can you give me a link to the update notes?  I'm not even sure where that is.

Thanks!

**Comment by kushariforyou** [comment]
Not sure where I could get that again. Just go to settings in the app, then go to developer options, it’s in there.

**Comment by thoots99** [comment]
I think I found it -- I searched for "SmartTube update notes."  :D  I have checked the suggested box, and am rebooting.  I'll see how it goes and report back.  Thanks -- this has been pretty unbearable!

**Comment by thoots99** [comment]
So far, so good -- "Settings/Video Player/Developer options/Buffering fix (experimental)".  Hopefully that'll be the end of the problem.  Thanks again for your help -- I really haven't dipped my toe into any of the innards of the app like this before.

**Comment by kushariforyou** [comment]
No problem! I was super lucky to notice it. I checked the change log and that was the notes.

**Comment by thoots99** [comment]
Thanks again -- that change has made life with SmartTube bearable again!

**Comment by thoots99** [comment]
OK, "I guess I spoke too soon."  I rebooted my NVIDIA Shield, and then went back into SmartTube -- "the problem is back!"  So, I went into the Developer Options, and -- call it good or bad as you wish -- the "buffering fix" box was NOT checked.  So, is this something I have to do EVERY time I launch SmartTube?  And then, even with it checked, I have STILL seen the "Video source isn't working or incorrect time" issue.  I just checked the box and started another video, and it's as bad as it has ever been.

To be specific, the video will stop playing.  The message, in a gray box at the bottom of the screen, displays the "Video source isn't working or incorrect time" message, then the screen will go black with a spinning icon, and then the video will continue playing.  Whatever is going on here, it sure is NOT fixed, and now that "buffering fix" isn't helping at all.  I've literally seen half a dozen instances of this while I've been typing out this message.  So, "still hoping for a solution to this issue," as it makes using SmartTube almost intolerable.  Thanks in advance for those who are working on things like this.

**Comment by thoots99** [comment]
Well, another update:  The "buffering fix" might help, but every time I go back to see if it's still checked, IT'S NOT CHECKED ANYMORE.  I have literally checked it, exited back to the menu, pulled up a video, and gotten the "Video source isn't working or incorrect time" issue.  Then I'll go right back into the settings, and the "buffering fix" IS NOT CHECKED.  It would appear that it worked for a while, but after moving around a bit to different videos, it just won't "stick" anymore.  I have literally gone back and forth with this, having problems with a video and going to see if the box is checked -- only to find it isn't checked anymore -- about half a dozen times.  So, is there some "trick" to make that box stay checked?  I'm stumped at this point.

**Comment by kushariforyou** [comment]
Is your operating system up to date? What version of android are you running?

**Comment by thoots99** [comment]
This is an NVIDIA Shield 2015, which NVIDIA has continued to update, and it is running NVIDIA's current version -- "SHIELD Experience Upgrade 9.11," released in November of last year.  I believe this is running NVIDIA's version of Android 11.

**Comment by thoots99** [comment]
I have been going back and forth, checking the box, exiting out of the Settings, then going back to see if the box is still checked, then starting a video, and going back to see if the box is still checked, and -- after another reboot -- it has stayed checked.  Though, it was after a reboot when "it stopped working," above.  I have to shut the computer down tonight and move along for now, but I'll keep banging my head against this one.  But it does appear that when the box is checked, it works.  But that box very often just won't stay checked.  That's the best I can say at this point.  I'll keep on sharing my experience with this issue.

**Comment by thoots99** [comment]
Following up.  The "buffering fix" seems to work, though I might have had a couple of very minor bumps here and there.  But this cannot be a "fix" for the problem, as the "buffering fix" checkbox will NOT be checked after I restart my NVIDIA Shield, and I've had a LOT of difficulty "keeping it checked."  I'm now trying to get my arms around that -- "So, what does it take to check that box and then move around in SmartTube without 'unchecking' it somehow?"  So, I'm still hoping for a full fix for this issue.  Thanks for kushariforyou's help through all of this!

**Comment by dontwantonebutneedone** [comment]
I was getting this on 4k/60 videos with high bitrates. Not on the latest version with the developer option for the fix checked. Been fine with that.

Nvidia shield 2019, latest updates to everything.

The only thing not working for me is the preview animations on the cards. Stopped working last week and whatever I set the options to, no animation.

**Comment by thoots99** [comment]
I never, ever saw the "Video source isn't working or incorrect time" until I said "OK" to the 17.26 version -- and then I started getting the error just about constantly.  Every other minute or so.  The "buffering fix" does seem to stop the "Video source isn't working or incorrect time" issue, but then the "buffering fix" checkbox won't seem to "stay checked" for reasons I haven't been able to figure out yet.  For instance, last night I was just watching one YouTube channel for a couple of hours, and after working just fine, I started getting the "Video source isn't working or incorrect time" issue -- and I literally had not interacted with my NVIDIA Shield at all.  "Never touched the remote control."  So, I went into the settings and looked -- and the box wasn't checked!  So, that box can "uncheck itself for no reason whatsoever???"  Whatever is going on here, I need a better fix than this.

That said, I suppose I should consider downgrading to a previous version, but I've never done that kind of thing with SmartTube.  If anyone has tips for doing that -- a link, or whatever -- I'm definitely considering doing that.  Thanks for everyone's help!

**Comment by thoots99** [comment]
Another update:  I'm happy to report that "the buffering fix checkbox has been behaving better."  I have actually been able to cold start or restart the NVIDIA Shield, then go into SmartTube and then into the Settings, and find that "the buffering fix box has still been checked."  Certainly, it was NEVER doing that, a couple of days ago.  I have no clue what's up with that, but if the box is checked, my problem is mostly solved.  I have still seen an occasional glitch -- like the audio will just drop out for a few seconds -- but that has been quite rare.  So, moving on with my life, and I'll pop back in here if there is any information worth mentioning.  Thanks again for everyone's help!

**Comment by kushariforyou** [comment]
There's a new update 17.35 that has "Another attempt to fix various playback problems like buffering/stuttering (especially on streams).

**Comment by thoots99** [comment]
Thanks -- and yes, I see it, a "Beta release."  But, I have questions about installing it.  I presume that I would install it "just like any other APK file," but....  Is that correct?  I also have all kinds of things configured -- like channels pinned to the sidebar, and so on.  Will just installing an APK wipe that out, or would that not happen?  Or is there some other way a different release like that should be installed?  Thanks in advance for your help on this, if you know how that works!

**Comment by kushariforyou** [comment]
I’m not sure in your case, because I get an update notification inside the app and it auto updates and then I can open the app again. All my login and preferences are preserved though, so I’d assume it would be, but I saw some other posts that said their stuff got wiped, so just be careful.

**Comment by thoots99** [comment]
Yes, I've seen some of those "other posts" -- "Yikes!"  And yes, I've always just installed updates as the app has prompted me.  I've done quite a bit of searching, but I haven't found much of anything relating to "what happens if you just 'install an APK file" to change to some other version.  You bet, that's a fire I won't just jump right into.  Frankly, the "buffering fix" seems to work quite well, but it's like "every time I come in here and say it's working consistently now," then within a few minutes, I get the "video source isn't working or incorrect time" error, and then go look and see that the "buffering fix" isn't checked anymore.

I can't really discern any rhyme or reason why that box gets unchecked, but it certainly won't stay checked, for some reason.  Still, it remains checked "most of the time" now, and that's far better than it was to begin with.  "A checkbox with a mind of its own."  Again, thanks for your help with all of this!

**Comment by thoots99** [comment]
OK, time for an update.  A new update was served to my system a few days ago -- presumably 17.39 "stable."  And I've been trying to "do nothing" but use the app as I normally would -- I haven't even checked to see if the "buffering fix" was checked.  But given my results with that, most likely it's not checked.  I'll provide an update about that, but for now, I really don't want to touch anything in the "settings" at all.

From what I can tell, 17.39 has fixed my problem.  I certainly haven't seen the "Video source isn't working or incorrect time" under 17.39, but I've seen a glitch or two.  But then, that kind of thing has always happened every now and then, so I would call that "unrelated."  Like, for instance, if I've been using the app for around 8 hours or more, I might get an audio dropout every now and then -- and rebooting my NVIDIA Shield fixes that.  Anything odd at this point seems to be "that kind of thing" -- nothing happens very often, and rebooting usually clears any issue for many hours.

So, thanks for everyone's help, and I just want to give it a few more days to confirm what's going on, and then I'll get back with more concrete information.

**Comment by thoots99** [comment]
Time for another update.  Indeed, this is 17.39 "stable," and the "buffering fix" checkbox is NOT checked.  And I have actually had two (2) "Video source isn't working or incorrect time" errors -- both during hours-long replays of livestreams that had been recorded a few days earlier.  These were like "around the sixth hour of a nine-hour video."  So, "not typical YouTube videos," by any means.  But yes, during two of these -- quite similar in length and after several hours of playing each video -- I saw one error, and that was the end of it.  Certainly nothing that would bother me like the problem originally did, when it was happening virtually all the time, over and over again.  But worth reporting, I presume.  Thanks again for everyone's help with this issue!

**Comment by thoots99** [comment]
VERY BAD NEWS.  I installed version 17.61 when prompted, and IMMEDIATELY got a couple of "Video Source Isn't Working or Incorrect Time" errors.  Absolutely going backwards on this now.  After having had enough of it, I went to try the "buffering fix," only to see it was GONE.  Unless it was moved somewhere or something like that.  I'm not getting the error as often as I would when I first joined this discussion, but I'm getting it far more often than the few times it happened during playing a couple of hours-long videos, with version 17.39.  So, this definitely hasn't "fixed" in my situation yet.  Nothing else has changed -- still using the NVIDIA Shield 2015 with up-to-date software version(s).

**Comment by thoots99** [comment]
So, here's a look at the problem I've been seeing under 17.61.  Almost every time I get the error, it happens within the first few seconds of the start of a video -- like the first 5 seconds.  I'll see the error message, the screen will go black -- and then, EVERY TIME -- the video will start over from the beginning.  I don't suppose I could say that EVERY time I've had the error, it has happened like this, but this is BY FAR the most prevalent way I have been seeing this.  Hope this helps.

**Comment by thoots99** [comment]
"Later that same day...."  I got the prompt to install version 17.62.  And "so far, so good."  As I mentioned above, I got some "Video Source Isn't Working or Incorrect Time" error messages almost immediately after installing 17.61, but I haven't seen anything at all with 17.62.  I'll report if I do see the error again, but again, no problems at all, at this point.  Thanks as always to everyone who keeps working on the updates!

**Comment by thoots99** [comment]
I just experienced my first "Video source isn't working or incorrect time" error on 17.62 -- exactly the same as I described above with 17.61.  The error happened a few seconds after a video started, then the screen went black, and then the video started over from the beginning.  Not the end of the world, but worth reporting.

**Comment by thoots99** [comment]
Well, that didn't last long at all.  17.62 is now throwing the "Video source isn't working or incorrect time" error on a regular basis -- I've seen it as often as I did with 17.61.  Version 17.39 was much, much, MUCH better.  Once again, usually the error comes right after a video starts, then the video restarts from the beginning.  Though, I've seen a couple of error messages in the middle of a video, and then it just stops, the screen goes black, and then the video resumes.

**Comment by thoots99** [comment]
NIGHTMARE!  17.62 has now become a basket case on my system.  I'm getting the "Video source isn't working or incorrect time" error on EVERY VIDEO I've played this evening.  I'm getting both the kind of error when it happens a few seconds after a video starts, and then the video completely restarts from the beginning, and also getting it at any time in the middle of a video, and then the screen goes black, and then the video continues.  EVERY video, ALL evening, so far.

**Comment by thoots99** [comment]
I've updated to 17.88, as prompted.  Effectively no difference with the "Video source isn't working or incorrect time" issue.  I'll get it probably on average of once per hour.  "Could be worse / has been worse."  Seeing it both at the beginning of videos and somewhere in the middle -- perhaps a bit more often in the middle as compared to previous versions.

**Comment by thoots99** [comment]
Just checking in to report that 18.15 hasn't improved "Video source isn't working or incorrect time" at all -- I'm still getting that error quite often.  Mostly right after starting playback of a video, and more often after choosing a video manually, as opposed to just "getting the next video" fed to me by YouTube.

**Comment by thoots99** [comment]
OK, so version 18.23 showed up yesterday, with the description of "The fix for the video source error."  So, I guess I'm in a good position to be a judge of that.  And while I haven't been watching 24/7, I've got quite a few hours of watching time done, with a variety of "usage patterns," or whatever you might call them.  So, what's the verdict?

Well, it's much, much better.  But I have had ONE (1) "Video source isn't working or incorrect time" error.  Which happened rather in the middle of a video that YouTube served to me.  Still, I probably got a dozen or more errors per day previously -- as described in the messages I have posted, above.  So, if that goes down to only one per day -- or hopefully fewer than that -- that's a big improvement, to be sure.

It might be worth mentioning that previously, "manually choosing a video to play" was always far more likely to generate the error compared to getting a video served to me by YouTube -- and the error would usually happen a few seconds after the video started.  And then the video would restart.  And so far with 18.23, I haven't experienced one of those, at all.

So, "so far, so good," and I'll give it a couple more days, and provide another update.  Thanks as always to everyone involved with working on this wonderful app.

**Comment by thoots99** [comment]
So, Version 18.27 just dropped, and I've installed it.  I'll see how that goes.  I can report that Version 18.23 actually gave me TWO (2) "Video source isn't working or incorrect time" errors -- the second about four hours after the first one.  Not "perfect," but a big improvement over previous versions.  I'll see how 18.27 goes.  Thanks as always to everyone involved with working on SmartTube.

**Comment by chuegel** [comment]
Same with 18.28 on shield. Can't playback any single video without this issue

**Comment by thoots99** [comment]
I'm a bit tardy with an update.  In a few words, "things have been going downhill" with releases since 18.23.  I've seen more and more "Video source isn't working or incorrect time" errors.  With 18.50, I'm pretty well back to getting one -- and sometimes two -- errors every time I "pull up a new video."  Same thing, every time -- within the first few seconds, I'll get the error, and the video will start over.  And then I might get a second one.  But when I just sit back and let YouTube "feed me the next video," it's far less likely that I'll get the error.

Oh, "it has been worse -- FAR worse."  But in the recent past, it has been almost completely gone.  "Not so much, anymore."

I should note that I have looked into the "player network stack option" -- which "might fix the error" -- but since I have absolutely no clue whatsoever what I should do with those options, or what they might or might not do, I haven't touched a thing in there.  If there is any information anywhere about what's going on with those, I might try them.  But I've rather learned not to screw around with things I don't know anything about, so I have continued not touching them with a virtual ten-foot pole.

Thanks again for everyone's help!
