### ISSUE TITLE
Unknown error 403 

### ISSUE THREAD

**Issue by karepiu** [yuliskov/SmartTube#3513]
Hi, been using Smart tube for feels years now.
Yesterday started to got 403 error after 60 seconds of playback on every video.
Initially thought that it may be related to update but I downgrsde to check and it was not it. 

Poked around more noticed that all works as long as I am not signed in.
Interestingly enough YouTube works when signed in and Smarttube does not work.

Did anybody seems something similar ?

**Comment by manchester-party** [comment]
Same issue here, Nvidia shield.

**Comment by jbb8** [comment]
Same. On Sony Android tv. Started happening about 2h ago

**Comment by UAVXP** [comment]
Same. Version is 21.90 beta

**Comment by tuuuubes** [comment]
I'm also experiencing this 403 error. 
I'm on Android TV (Version 9).
SmartTube beta version 21.90

**Comment by Yok333** [comment]
Unknown error Response code: 403
Android tv. 
Help

**Comment by Yok333** [comment]
I got a new update 21.91
It seems to work for me 😀

**Comment by Ra1Del** [comment]
Same issue: Unknown error Response code: 403
Version 21.91 didn't fix it, downgrading also didn't help.
TV has android 9
Error appears on some videos while others play fine, music videos mostly affected .

Tried switching users, reinstalling app(Deleting all data), messing with playback settings, issue persists.

Regular youtube app works fine.

**Comment by Yok333** [comment]
I forgot to mention that I changed the installation location. It was installed on an external drive and I changed it to be installed on the TV instead.  Everything is working fine now.

**Comment by CubsCreeper** [comment]
same issue here update didn't fix it help

**Comment by lukolszewski** [comment]
Any ideas how to solve this? Just happened today. Tried unpgrading, logging out, nothing helps.

**Comment by pfiebig** [comment]
Same problem. 🤔

**Comment by kidquick** [comment]
Just happened to me too. Fixed it on my Android TV by going to Settings -> Apps -> Smart Tube beta -> Force Stop and Clear Data. Hope that helps!

**Comment by pfiebig** [comment]
> Just happened to me too. Fixed it on my Android TV by going to Settings -> Apps -> Smart Tube beta -> Force Stop and Clear Data. Hope that helps!

Sir, you are the best and the saving grace of my evening. may your pillow always be soft and fluffy. helped me a lot, thank you.

**Comment by DragonWolf5589** [comment]
Started to get this error myself today. Its up to date etc

**Comment by vodnik33** [comment]
nVidia SHIELD last version 22.37 Unknown error  Response code 403

**Comment by Pnether** [comment]
Firestick gives the same error. Response code: 403

**Comment by Pnether** [comment]
Also on Firestick and Chromecast with remote: error Response code 403.

**Comment by megaspaz** [comment]
22.37 of ambV7 asset installed and showing `Unknown source error Response code: 403` on every video attempted playback.

**Comment by jameelbaaz** [comment]
Same issue after update also

**Comment by jere19** [comment]
Same issue on v22.37. It still works on live feeds it seems, but not on regular videos.

**Comment by michaeleangelo** [comment]
> Keep getting "Unknown Source error. Response code: 404"

Error 403 maybe? the thread is not about 404.

**Comment by itsmir** [comment]
Same 403 error here on v22.37. Nokia box 8000 A12.  Clean install, no user and with user, all playback gives 403 error

**Comment by knallie** [comment]
Same issue here with 
- SmartTube 22.37
on
- Fire TV Stick 4K Max with Fire OS 7.6 7.3

**Comment by djordjeradovic** [comment]
Same here, error 403 on all videos.

SmartTube 22.37 on TOX3 with Android 11

**Comment by sippeeey** [comment]
Same Here 22.37
Amazon fire tv 4k

**Comment by siddheshshivgan** [comment]
Tried with 21.91 and latest too. Nothing works 😞

**Comment by TheTingler** [comment]
I tried one live feed and it didn't have the error code on it.  I don't know if that helps. I'm using a TiVo stream 4K and it has the issue. Didn't have it till I downloaded the new version though I didn't have it earlier I just updated to the latest and then I got the issue.

**Comment by Darrendakid** [comment]
Same here amazon fire stick has been saying unknown source error, response code :403…is the app dead ?

**Comment by djordjeradovic** [comment]
I had some older version and it stopped working today so I updated to latest but it didn't help...

**Comment by SabreNation** [comment]
Same issue here on Firestick. 

App was working fine all day yesterday and today up until about 20 minutes ago. I noticed there was an update so I installed it and now I get the 403 error on every video I try to play. It was working right up until I installed that update. 

I tried all of the various workarounds posted here and around the web. Cleared cache, cleared data, uninstalled, reinstalled, tried both stable and beta. Nothing works.

**Comment by TheTingler** [comment]
Live Broadcast works

**Comment by arjun-calidas** [comment]
NVidia shield pro here. Installed an update about 30 or so minutes ago and nothing but live streams work..

**Comment by Bahazzie** [comment]
Too bad if this is the end for this brilliant app. Wasting time on commercials is EVIL.

**Comment by Bahazzie** [comment]
(Nvidia Shield, happy user for years now same 403 error)

**Comment by akas3rious** [comment]
Error 403 Android TV, force stop and cleaning data doesn`t help, stream works, video (shorts) - don`t

**Comment by barneyz** [comment]
update today to 22.37 FireTV-Stick 4k 403 error on all videos

2nd  FireTV-Stick 4k  i updated yesterday to 22.19, first time 403 error on all videos, update to 22.37 again 403 error on all videos

**Comment by RobertWhitlet** [comment]
Any alternative apps to SmartTube just in case SmartTube is over?

**Comment by kidquick** [comment]
As mentioned above, I got mine to work again after a Force Stop and Delete Data/Cache. I never uninstalled it. However I had also logged out of SmartTube and then back in a couple times, rebooted my device (TCL Android TV) and updated my router-based ad filter (Diversion). So it could have been any combination of those, but I believe it was the Force Stop and Delete Data that did it.

**Comment by aviadlevy** [comment]
Force stop and delete data not working. Still error

**Comment by RobertWhitlet** [comment]
On SmartTube patreon, they say they're aware of the 403 error code and are working on a solution

**Comment by somfink** [comment]
Error on TCL Android TV

**Comment by dalai-lamia** [comment]
Nothing helps... I've done force stop, clear cache, clear all data, sign in again (with activation in browser) twice already. Can't play a single video. Looking forward to an update that fixes this. Keep up the good work, devs!

**Comment by rideordieguy** [comment]
Let me start by saying thank you for the years of annoyance free viewing and the AWESOME app that yall put together.

Now...I just installed 22.37 about 5 minutes ago to try and resolve the 403 error I am having since last night on my firecube and it didn't work. Live still plays but nothing else. Weird thing is it was working fine on my Toshiba tv with built in fireTV all last night and today mostly until about an hour ago and that one stopped working too. I wonder what was the difference and if that info may help the devs come out with a 403 fix that actually works. NOT knocking the devs at all, just trying to help. 
![17205513064309059812672270219963](https://github.com/yuliskov/SmartTube/assets/175153825/f6f0f201-1774-42fd-81a9-486abd45e9ba)

**Comment by karepiu** [comment]
Did you try logging into different account ?

This was what helped me before

**Comment by dalai-lamia** [comment]
> Did you try logging into different account ? This was what helped me before

I don't have a different account.

**Comment by Itsjustahobby** [comment]
> Did you try logging into different account ? This was what helped me before

This didn't help me by the way (AndroidTV) so I'm going to entirely assume the DEVs are having the problem on their end with the update of Youtube like someone in this thread mentioned instead of it being account-based.

**Comment by Jokers1235674** [comment]
I report the same problem, I hope code 403 is solved soon.

**Comment by Enet-Ls** [comment]
On my TV station it works very well.  I have not yet applied the update.... (the update is available I have not yet installed it) whereas on my free box player it does not work (I did the  update available on this support)... if that helps.
(From france)

**Comment by TheTingler** [comment]
https://support.google.com/youtube/thread/269521462/enforcement-on-third-party-apps?hl=en

**Comment by RomanoRC** [comment]
I'm having the same error code and problem.  Update didn't work, clearing cache and data didn't work. Force stop didn't work.

If the devs fix it, will they release the update on the app or from here?

**Comment by derdems** [comment]
> https://support.google.com/youtube/thread/269521462/enforcement-on-third-party-apps?hl=en

Well that's it, then?
I'd say we had a good run...

**Comment by Reganyr** [comment]
Bonsoir, 
Même problème, j'utilise SmartTube depuis plus de 2 ans et c'est la première fois que je suis confronté à ce problème d'erreur 403. Aucune vidéo ne s'ouvre. J'ai désinstaller Smart, réinstallé. Puis désinstallé pour installer Smart Beta. J'ai vidé le cache. Arrêté l'appli puis redémarré. J'ai redémarré la télé Android TV. Rien de rien! J'ai même réinitialisé la Télé Android pour repartir à zéro. Rien. Je suppose que les développeurs vont nous faire une mise à jour? Merci en tous cas pour ces 2 années sans le Youtube de Google infecté par leurs pubs. NB: j'ai le même problème sur mon Galaxy S23. Bonne soirée.

**Comment by RomanoRC** [comment]
> > https://support.google.com/youtube/thread/269521462/enforcement-on-third-party-apps?hl=en
> 
> Well that's it, then? I'd say we had a good run...

Hope not. I can't stand those flippen ads so often on a video.

**Comment by spockers** [comment]
> > https://support.google.com/youtube/thread/269521462/enforcement-on-third-party-apps?hl=en
> 
> 
> 
> Well that's it, then?
> 
> I'd say we had a good run...

Cat vs mouse, this is just a flesh wound. Hopefully.

**Comment by Tarhbox** [comment]
Ne fonctionne plus également sur Bbox Miami 😭😭 Espérons que ça refonctionne très vite. Les pubs me rendent dingue.

**Comment by vmsman** [comment]
Interesting points made here.  I have also seen the error on SmartTube  and SmartTubeNext.  Interestingly, on the Linux app "FreeTube" it is able to still play all content with commercials suppressed.  FreeTube sees an "API Error" but plays nontheless.  Perhaps if DevOps are monitoring this may be helpful.

**Comment by kidquick** [comment]
> https://support.google.com/youtube/thread/269521462/enforcement-on-third-party-apps?hl=en

That's a relevant article, however it is from April 15, 2024. Hopefully the devs can find a workaround... ad blocking aside there's so many other great features that the official YT app doesn't have.

**Comment by SZTSIIT** [comment]
I have to install this legacy version one for now and it works. https://github.com/yuliskov/SmartTubeLegacy

Peace Guys
🤘🏼🤘🏼🤘🏼

**Comment by megaspaz** [comment]
> I have to install this legacy version one for now and it works. https://github.com/yuliskov/SmartTubeLegacy
>
>Peace Guys
>🤘🏼🤘🏼🤘🏼

No joy... Same Error for me...

**Comment by xnymphie** [comment]
I got the same error after updating today. Strangely, it only effects normal videos. I can still view youtube streams as long as they are still live

**Comment by beginrescueend** [comment]
> Firestick gives the same error. Response code: 403

Confirmed - all videos 503, before or after the latest update.

I even tried to stop / clear cache / clear data. 403's for everything. :-(

**Comment by Spencer-Lim** [comment]
Live streamings are normal, only the video files streaming error. I think Youtube's server banned this App.

**Comment by Reganyr** [comment]
Cette dictature signée "Google" ne m'étonne pas

**Comment by GurgenWolkov** [comment]
Sinse last evening "unknown error source. Error 403 "
Update 23.37 did not help.

**Comment by xtornado** [comment]
Same issue, tried everything

**Comment by UAVXP** [comment]
Why people are bumping this issue? What's the point?
Everyone has this, and if not - they will. Devs aren't going to have advantage if a GitHub user @ilovemymommy answers "Same issue, 403, tried everything and every version" in a thread, where this bug has been mentioned for about a 100 times

**Comment by DrJaymz** [comment]
I have also noticed at the same time when a YouTube video is in a google search result (where it shows the highlighted portion of the video) that also stopped working at the same time.  Thats mildly interesting because they broke their own product.  With regard to smarttube I had it working on one TV but not on the other at the same time, same version; suggesting it is on a client by client basis.

**Comment by Pnether** [comment]
After 2 years of making use of this excellent software, and some in-between donations, I donated again right now, to encourage the development team to solve this error. That seemed the right thing to do for me.

**Comment by Reganyr** [comment]
> > Pourquoi les gens soulèvent-ils ce problème ? Quel est l'intérêt ? Tout le monde a cela, et si ce n'est pas le cas, ils le feront. Les développeurs n'auront aucun avantage si un utilisateur de GitHub@IloveMymommyrépond "Même problème, 403, j'ai tout essayé et toutes les versions" dans un fil de discussion, où ce bug a été mentionné environ 100 fois.
> > Ce n'est pas comme sur YouTube, où les créateurs disent « Atteignons 100 000 likes et je ferai un autre épisode » ou un truc du genre. Ce ne sera pas « Atteignons 500 commentaires sur un problème et je corrigerai ce bug », les gars.
> > Calme-toi et attends, s'il te plaît. Ton commentaire "sAaAaAme" ne t'aidera pas
> 
> Je suis d'accord

Bonjour reloxx13, vous avez certainement raison. Mais je pense que quand il y a un grand nombre de signalements, aiderait peut-être le développeur a évaluer l'ampleur de la panne et que ça touche beaucoup de fan de SmartTube. En plus, il n'y a pas de mal à signaler. Personnellement, je ne suis pas très technique et mon signalement n'a rien à voir avec les "j'aime" ou "n'aime pas". Bonne journée à toutes et à tous. Et comme dit "relox", patientons et faisons confiance au développeur!

**Comment by hjkgugy345** [comment]
For now helped me making YT Premium account (1st month for free). After login to smarttube by that YT Premium account evetything works fine. This temporary solution let you watch YT by smarttube (for free) until dev fix the problem.

**Comment by Smithie63** [comment]
I solved it by installing Brave browser on my android phone/tablet, YouTube and free works great even when signed in I believe works the same on ios

**Comment by Reganyr** [comment]
> Pour l'instant, cela m'a aidé à créer un compte YT Premium (1er mois gratuit). Après m'être connecté à smarttube via ce compte YT Premium, tout fonctionne correctement. Cette solution temporaire vous permet de regarder YT via smarttube (gratuitement) jusqu'à ce que le développeur résolve le problème.

Bonjour hjkgugy345, croyez-moi, c'est exactement ce qu'il ne faut pas faire car, c'est ce que cherche à nous faire faire le "Rapace" Google. Non, il faut résister et attendre une solution. Personnellement, je ne paierais même pas un €uro troué pour passer à Youtube Premium et je n'en mourrai pas!!! C'est en tous cas ma conviction!

**Comment by hjkgugy345** [comment]
> Bonjour hjkgugy345, croyez-moi, c'est exactement ce qu'il ne faut pas faire car, c'est ce que cherche à nous faire faire le "Rapace" Google. Non, il faut résister et attendre une solution. Personnellement, je ne paierais même pas un €uro troué pour passer à Youtube Premium et je n'en mourrai pas!!! C'est en tous cas ma conviction!

I agree with you, but like I write before - this is temporary solution until dev fix the problem. When it will be fixed you can cancel (free for 1st month) YTPremium subscription.

**Comment by DrJaymz** [comment]
> > Bonjour hjkgugy345, croyez-moi, c'est exactement ce qu'il ne faut pas faire car, c'est ce que cherche à nous faire faire le "Rapace" Google. Non, il faut résister et attendre une solution. Personnellement, je ne paierais même pas un €uro troué pour passer à Youtube Premium et je n'en mourrai pas!!! C'est en tous cas ma conviction!
> 
> I agree with you, but like I write before - this is temporary solution until dev fix the problem. When it will be fixed you can cancel (free for 1st month) YTPremium subscription.

Grayjay also works - this is probably because I read that it still works if you are not signed in, so grayjay handles your subscriptions separately and probably pulls the file without being logged in.  

At the end of the day, if its possible to watch the video in a browser it can always be got around.  Even if the a ghost browser has to watch the ads and then strip them it can be done.  YouTube's next thing is to encode the ads into the video itself on the fly, preventing any software knowing where they moved it to.  YouTube needs to watch its step because whilst its trying to take ever increasing bites of profit, its driving away content producers and users alike.  The last straw for me was when it started showing me adverts in my own videos as if they think they own my video.

**Comment by Reganyr** [comment]
D'accord mais si jamais Google serait à l'origine de cette panne (ce qui n'est pas étonnent) et que SmarTube devient définitivement hors service, que feriez-vous? Renonceriez-vous au Youtube Premium? C'est ça le problème en fait. Google a les moyens de saboter SmartTube ou tout autre application. Personnellement, je n'ai aucune confiance en Google. J'espère que la Communauté européenne étudierait bien ce sujet et projetterait des sanctions contre le géant américain. Elle l'a déjà fait par le passé contre lui et bien d'autres. Pourquoi pas pour "Publicité abusive" qu'il nous impose?. En tous cas je ferai tout pour attirer l'attention de Bruxelles à ce sujet!

**Comment by 1980103siva** [comment]
now working 20.38

**Comment by hjkgugy345** [comment]
> now working 20.38

Changelog say, that it's only fullhd? Is it right?

**Comment by Pnether** [comment]
version 22.38 works on my Firestick ! Many thanks !!

**Comment by rithvik010** [comment]
Updated to 22.38 in android tv but still unknown source error 403 coming
Did any found solution

**Comment by DrJaymz** [comment]
> version 22.38 works on my Firestick ! Many thanks !!

Confirmed, both of mine now work. (or youtube has had to back the changes out).

**Comment by WoodyXXL** [comment]
with 22.39 no fix for -> Fire TV Stick 4K Max (Reboot....)

Same 403 Error.

**Comment by jackieapp50** [comment]
> with 22.39 no fix for -> Fire TV Stick 4K Max (Reboot....)
> 
> Same 403 Error.

Did you try going in the settings in the app and clicking the download, it works

**Comment by WoodyXXL** [comment]
> > with 22.39 no fix for -> Fire TV Stick 4K Max (Reboot....)
> > Same 403 Error.
> 
> Did you try going in the settings in the app and clicking the download, it works

Yes, that's why I received the update to 22.39.

**Comment by TheTingler** [comment]
> > https://support.google.com/youtube/thread/269521462/enforcement-on-third-party-apps?hl=en
> 
> That's a relevant article, however it is from April 15, 2024. Hopefully the devs can find a workaround... ad blocking aside there's so many other great features that the official YT app doesn't have.

Yes, they started earlier this year. Ramping up. Didn't say that they already did it. It said they were starting to do it.

**Comment by WoodyXXL** [comment]
> I meant download the update in there

Yes - now its up-to-date.

**Comment by RomanoRC** [comment]
Working here now with the new update. Luckily my network is managing so far with full HD. Currently have a 25mbps speed

**Comment by donb108** [comment]
I just installed the update, via the "Update" selection in the Smarttube app, then power-cycled my adapter (Onn stick).  I tried regular videos for a few seconds; seems to be working.

**Comment by GamingXtutti** [comment]
Update to 22.39 work AndroidTV Philips , firestick basic and Firestick 4k. Thanks ❤️

**Comment by rideordieguy** [comment]
Hallelujah ....Hallelujah....HallelUUUUJAAAAAH! Big Ups to the devs! GREAT JOB Y'ALL!..... AND THANK YOU! 22.39 installed and 403 issues resolved. 

EVERYONE HERE THAT CAME TO POST ABOUT THE 403 NEEDS TO DONATE TO THE CAUSE! They did a great job getting it fixed, Especially for a FREE APP with so many features and advanced functions that ACTUALLY work. 

If you don't know how: scroll to settings in the app. Then click "about" and then "donate" and pick one, scan the QR code and throw the devs a bone that they more than deserve. 

No I don't work for them or know them.....I Just really like the app and it takes an outage like this and skipping ads manually for 2 days to realize how great this app **_really_** is!

**Comment by Reganyr** [comment]
> Mise à jour vers 22.38 sur Android TV mais l'erreur 403 de source toujours inconnue arrive Avez-vous trouvé une solution



> rithvik010
Je viens de recevoir la màj version 22.38. Je l'ai téléchargée et sans redémarrer ni rien d'autre, SamrtTube fonctionne de nouveau!

**Comment by Reganyr** [comment]
> la version 22.38 fonctionne sur mon Firestick ! Merci beaucoup !!

Pareil sur Android TV.

**Comment by Jokers1235674** [comment]
After updating to version 22.38, error 403 seems to be solved

**Comment by CharlesCumstein** [comment]
You know, you don't realize how convenient this app is until it's not working. I sent a donation to the developer, Yuri. The guy more than deserves it. These ads, while I get why they're there, are annoying and anyone who can help my bypass that deserves a few bucks to buy a coffee at the very least. Hey Yuri thanks again, bud. Keep up the great work!

**Comment by kkrusher741** [comment]
Just installed the latest update and it works so far. Thanks!

**Comment by dalai-lamia** [comment]
Unfortunately, still no joy on Android TV even after updating to 22.39 and resetting the app.

**Comment by jackieapp50** [comment]
I'm using a firestick and was having same problems, you have to go onto Smartube,  - settings, (i) for information and select the update, it will work, I've done it on all 3 of mine and working as usual now, hope it works for you.

**Comment by WoodyXXL** [comment]
> Unfortunately, still no joy on Android TV even after updating to 22.39 and resetting the app.

Same here - maybe 22.38 running and 22.39 not running? 

Version 22.39 - Test with delete cache and data & Reboot -> no fix 😭😭😭 for Fire TV Stick 4K Max (Fire OS 7.6.7.3 (PS7673/4183)

Live is working - other videos -> error 403 😭😵‍💫😭

**Comment by jackieapp50** [comment]
I'll have too until I can sort out with Aria xx

**Comment by Atrain151** [comment]
> Unfortunately, still no joy on Android TV even after updating to 22.39 and resetting the app.

Same on my nvidia shield pro and fire 4k max, running 22.39

**Comment by Herijgers45** [comment]
I used thé update and now it works.

**Comment by Enet-Ls** [comment]
Too
Tanks to devs

**Comment by xnymphie** [comment]
Unfortunately the new update is not working for me. I did go to the settings to download the update. Still getting the 403 error but can view live streams 

But brave browser works, I just really like the ui of this app

**Comment by xnymphie** [comment]
> Unfortunately the new update is not working for me. I did go to the settings to download the update. Still getting the 403 error but can view live streams
> 
> But brave browser works, I just really like the ui of this app

Okay, I forced closed the app and cleared the cache as someone two days ago suggested.  I waited a few minutes and now it's working. Ty devs will donate

**Comment by WoodyXXL** [comment]
> > Unfortunately, still no joy on Android TV even after updating to 22.39 and resetting the app.
> 
> Same here - maybe 22.38 running and 22.39 not running?
> 
> Version 22.39 - Test with delete cache and data & Reboot -> no fix 😭😭😭 for Fire TV Stick 4K Max (Fire OS 7.6.7.3 (PS7673/4183)
> 
> Live is working - other videos -> error 403 😭😵‍💫😭

22.41 is now working! Thx a lot!

Fire TV Stick 4K Max (Fire OS 7.6.7.3 (PS7673/4183)

Not working: 22.38 & 22.39

**Comment by jackieapp50** [comment]
I downloaded the update in the smartube app via settings -then select information - update, its even works again on my android phone no problems.

**Comment by beginrescueend** [comment]
Today's brand new version works again on Firestick, so far! (No 403's)...

Thanks for the quick turn-around.

**Comment by najibla** [comment]
Works again on my Sony TV.

**Comment by dalai-lamia** [comment]
Version 22.41 works on my Android TV, too! Good job!

**Comment by s3327445** [comment]
Can your device turn on 4k? Although the 403 error has been solved, 
4k cannot be watched, and the audio cannot be decoded by opus.

**Comment by DDSK15** [comment]
Updated the existing installation to v22.41, but it's still not working on Nvidia Shield. Then I uninstalled and reinstalled the app, and still no joy.

**Comment by PororoManon** [comment]
I fix this, at least on my xiaomi TV stick.

i installed beta 22.41. at 1st tried, it still show 403. after that I read someone said can play live but not uploaded video. So I try play live video. I can do that too. after that I play video again, surprisingly I can play the video normally.

**Comment by DrJaymz** [comment]
I very much doubt that invalidating the session information is going to work for very long because its obvious on their end when you're not receiving ads.

**Comment by ar2wee** [comment]
Version 22.39 working on Samsung TV

**Comment by RomanoRC** [comment]
Hi guys, it's not working my side. The first new update fixed it then it went back to the error. I then updated to the latest one and still not working.

Hope there's a fix soon

**Comment by ar2wee** [comment]
install the Version 22.39.Itworking for me.    пятница, 12 июля 2024 г. в 18:08:20 GMT+1, RomanoRC ***@***.***> написал(-а):  
 
 


Hi guys, it's not working my side. The first new update fixed it then it went back to the error. I then updated to the latest one and still not working.

Hope there's a fix soon

**Comment by Reganyr** [comment]
> installer la version 22.39. Cela fonctionne pour moi. vendredi 12 juin 2024 à 18:08:20 GMT+1, RomanoRC ***@***.***> a écrit(-a) : Salut les gars, ça ne fonctionne pas de mon côté. La première nouvelle mise à jour a résolu le problème, puis l'erreur est revenue. J'ai ensuite mis à jour vers la dernière version et cela ne fonctionne toujours pas. J'espère qu'il y aura bientôt un correctif - Répondez directement à cet e-mail, consultez-le sur GitHub ou désabonnez-vous. Vous recevez ceci parce que vous avez commenté. ID du message : ***@***.***>

Bonsoir ar2wee. depuis 2 jours, la mise à jour vers 22.38 est arrivée sur mon Android TV, je l'ai installée et tout est rentré dans l'ordre. Donc, essayez cette version: 22.38. Bonne chance.

**Comment by Reganyr** [comment]
> Bonsoir ar2wee. depuis 2 jours, la mise à jour vers 22h38 est arrivée sur mon Android TV, je l'ai installé et tout est rentré dans l'ordre. Alors, essayez cette version : 22.38. Bonne chance.



> Salut les gars, ça ne marche pas de mon côté. La première nouvelle mise à jour a résolu le problème, puis l'erreur est revenue. J'ai ensuite mis à jour vers la dernière version et ça ne marche toujours pas.
> 
> J'espère qu'il y aura bientôt une solution

Bonsoir. depuis 2 jours, la mise à jour vers 22h38 est arrivée sur mon Android TV de marque "SMART TECH, je l'ai installée et tout est rentré dans l'ordre. Alors, essayez cette version : 22.38 pour voir. Bonne chance.

**Comment by RomanoRC** [comment]
> install the Version 22.39.Itworking for me. пятница, 12 июля 2024 г. в 18:08:20 GMT+1, RomanoRC ***@***.***> написал(-а): Hi guys, it's not working my side. The first new update fixed it then it went back to the error. I then updated to the latest one and still not working. Hope there's a fix soon — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Doesn't work

**Comment by WoodyXXL** [comment]
22.41 is now working! 

Fire TV Stick 4K Max (Fire OS 7.6.7.3 (PS7673/4183)

Not working: 22.38 & 22.39

**Comment by ar2wee** [comment]
I install 22.39 Version.Then I clear data and cash<then restart TV and everything start working.

**Comment by RomanoRC** [comment]
It was working this morning and now nothing plays ...no error shows, video just had that loading circle.

**Comment by ar2wee** [comment]
for me still working 22.39 Version.No any problems....no any errors.
    суббота, 13 июля 2024 г. в 14:38:27 GMT+1, RomanoRC ***@***.***> написал(-а):  
 
 


It was working this morning and now nothing plays ...no error shows, video just had that loading circle.

**Comment by kkrusher741** [comment]
Wasn't getting error 403 until the last two updates. Now I get error 403, but pauses for a few seconds and then the video continues.

**Comment by Reganyr** [comment]
Bonjour,
Pareil, hier j'ai reçu la version 22.69 et bien sur, je l'ai installée. Et à l'ouverture de la première vidéo, l'erreur inconnue 403 est apparue. Elle reste affichée pendant 30 ou 40 secondes ensuite elle disparait et la vidéo s'ouvre.

**Comment by DrJaymz** [comment]
Mine were all updated last week, one yesterday showed 403 error but I didn't wait to see if it opened the video, I chose another video and it played fine.  I use daily so will see if it crops up again.

**Comment by kkrusher741** [comment]
Just got another update for error 403. Do we need to install it if we haven't been getting error 403??

**Comment by CubsCreeper** [comment]
> Just got another update for error 403. Do we need to install it if we haven't been getting error 403??

Well if you read the update it clearly states don't update if you haven't got 403

**Comment by kkrusher741** [comment]
> > Just got another update for error 403. Do we need to install it if we haven't been getting error 403??
> 
> Well if you read the update it clearly states don't update if you haven't got 403

The previous update said that, but the last update didn't.

**Comment by CubsCreeper** [comment]
> > > Just got another update for error 403. Do we need to install it if we haven't been getting error 403??
> 
> > 
> 
> > Well if you read the update it clearly states don't update if you haven't got 403
> 
> 
> 
> The previous update said that, but the last update didn't.

i just updated once i didn't know about any new ones

**Comment by Reganyr** [comment]
Bonsoir. En France, j'ai eu le problème 403 le 30 juillet au soir suivi d'une mise à jour. 403 a quand-même perduré. Je suis allé aux Paramètres de Android TV et j'ai vidé le cache. Ensuite, dans l'application SmartTube: Paramètres, puis "Sauvegarder/Restaurer", là, j'ai tout restauré et ça a marché. Le lendemain, le problème 403 est réapparu de nouveau. Et de nouveau, suivi d'une mise à jour et ça marche à ce jour du 1er août.

**Comment by RazMosneagu** [comment]
Updated to 22.81, the 403 error still persists on my MI TV 4K Stick
