### ISSUE TITLE
[BUG]: Please log in/sign in on 95% video.

### ISSUE THREAD

**Issue by rogacz1988** [yuliskov/SmartTube#4320]
### Checklist

- [x] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [x] This issue contains only one bug.

### Affected version

25.24

### Device Type

Smart TV/Box

### Affected Android

MiBox

### Steps to reproduce the bug

Open any movie.
Watch 2-3 another.
You cant watch 99% next after them.

### Actual behavior

I can't watch more than 2-3 movies.

### Additional information

Expected behaviour - on stable app i can watch all movies.

**Comment by BluebxrryMocha** [comment]
I figured out that if you keep a video that can actually play paused for a long period of time, it’ll give you the usual 403 error and then go back to how it was before the “Please sign in” shenanigans. And if another 403 error pops up it just goes back to doing this stuff.

**Comment by thembaxaba157** [comment]
The release beta claiming to fix unplayable videos, v26.06 I still have the same issue where most of the videos say ''Please Sign in''

**Comment by robosledger** [comment]
I was experiencing this also. I went to Settings> Accounts and the account was on None. I selected my account, and then exited the app by hitting the Back button twice. I launched the app again, and the problem was resolved. This only works for a while. I had to do it a few days ago also, then it was good for a few days.

**Comment by thembaxaba157** [comment]
The release beta claiming to fix unplayable videos, v26.07 I still have the same issue where most of the videos say ''Please Sign in''

**Comment by joao-matos** [comment]
I have this issue too.
I don't think it's the app. YouTube blocks my IP after watching a few videos in SmartTube.
Last stable on Android 11.
 I know this because I also use PipePipe yt client on my phone and it also stops working when SmartTube starts saying please sign in.
It never happened before started using SmartTube, I'm guessing because on PipePipe I've never watched as many videos as I do on my TV with SmartTube.
If I use the signed in official YT client on the TV while SmartTube and PipePipe are being blocked it works, but the other clients don't.
I'm going to test the theory that YT is forcing people to use accounts by creating and adding an account to SmartTube and report later.

**Comment by joao-matos** [comment]
I have confirmed the theory. Adding an account to smarttube makes the videos play again - through the signed in account, the anonymous / guest account still stays blocked.
From yesterday's experience this IP blocking lasts around 12 hours.

**Comment by ACR-Jeff** [comment]
Marking as Stale Due to a high volume of stale issues, It is possible this issue has been resolved by a more current version.

Please feel free to resubmit your issue if you believe it has not been appropriately dealt with, and tag this issue in the "Additional Information" section.
