### ISSUE TITLE
[BUG]: Unknown Source error 403 Loop

### ISSUE THREAD

**Issue by ACR-Jeff** [yuliskov/SmartTube#4366]
### Checklist

- [x] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [x] This issue contains only one bug.

### Affected version

25.89 Beta

### Device Type

Smart TV/Box

### Affected Android

Android TV version 9

### Steps to reproduce the bug

Open SmartTube
Try to play any video
Results in error

### Actual behavior

Videos not playing, Popup error with the message below in a continued loop non stop refreshing and throwing the same error over again.
```
Unknown source error 
Response code: 403
Don't close the player. Applying the fix...
```

### Additional information

Nvidia Shield 2017 (8.2.3) Android tv version 9

**Comment by ACR-Jeff** [comment]
Well it mysteriously fixed itself after a while, Possibly YT breaking things again. Closing this for now.

**Comment by ACR-Jeff** [comment]
Well this issue just keeps reappearing, So this is being reopened.

**Comment by Billo555** [comment]
Seeing same on a firestick.
Have updated to v25.87

It's asking me to sign in which I never do.

**Comment by ACR-Jeff** [comment]
Version 25.08 Stable still works. But the newest update 25.89 Beta continues looping with error above.

**Comment by ACR-Jeff** [comment]
Well this has spread to my stable version 25.08 and the most recent version 25.90 Beta solved it for a short time, Yet 25.90 Beta with a VPN doesn't play any videos, version 25.08 Stable with a VPN the videos play without issue so far.

**Comment by ACR-Jeff** [comment]
Update beta 25.91 seems to have solved this. I will keep this opened for now while doing more testing.

**Comment by Billo555** [comment]
I installed the beta. V25.92
Worked for 3 videos.
Now doing the same.

**Comment by ACR-Jeff** [comment]
Same here, Updated to v25.92 Beta same issues, Stable v25.08 still running strong on my end.

**Comment by ACR-Jeff** [comment]
25.97 Beta has fixed this issue on my end. Thank you

**Comment by ACR-Jeff** [comment]
Well that was short lived, It continues after some time with the error I originally posted. I guess I am sticking with the Stable v25.08 for now. Appears possibly YT causing this error?

**Comment by a60wattfish** [comment]
I've been having the same issue for the last 4 days. The odd video will play straight away, but most of the time I'm getting 403 errors. If I wait a long time the video does eventually play without issue (5+ minutes)
I've been using the latest betas and stable versions and tried clean installs of both.

**Comment by yuliskov** [comment]
I'm testing the possible fix right now. Is anyone willing to test? Installed over the existing beta.

[latest SmartTube_beta_testing.apk (download)](https://github.com/yuliskov/SmartTube/releases/download/latest/SmartTube_beta_testing.apk)

**Comment by 0o0will0o0** [comment]
> I'm testing the possible fix right now. Is anyone willing to test? Installed over the existing beta.
> 
> [latest SmartTube_beta_testing.apk (download)](https://github.com/yuliskov/SmartTube/releases/download/latest/SmartTube_beta_testing.apk)

Still getting the same error with this update

**Comment by ACR-Jeff** [comment]
> I'm testing the possible fix right now. Is anyone willing to test? Installed over the existing beta.
> 
> [latest SmartTube_beta_testing.apk (download)](https://github.com/yuliskov/SmartTube/releases/download/latest/SmartTube_beta_testing.apk)

Just installed and everything is working at the moment, If it continues is there a specific way to get a logcat for SmartTube? I would be happy to provide some logs when issues arise, If that would help?

**Comment by ACR-Jeff** [comment]
Worked just fine last night, Now it's doing exactly like all of the other previous updates. Looping the 403 error

**Comment by Saint8252** [comment]
Mines doing same thing on 26.06 beta. Been on and off for weeks it seems. Ill do update then seems to work for a day or so, then starts again. Do next update then fixed for a little bit.

Weird also is that sometimes it certain shows or streamers. Most videos will work, but Ill have like a Disney stream that wont load no matter what.

**Comment by ankitydv193** [comment]
I'm on the 26.06 and still have the issue but I founf restarting the TV makes it work again. Maybe that can help you to pinpoint the problem.

**Comment by Billo555** [comment]
I found that restarting my router usually helped so wondered if it's doing some kind of blocking by IP.

**Comment by senorsombrero** [comment]
Latest beta version doing the same on my fire stick. No videos at all playing

**Comment by Fire-** [comment]
yeah I can't watch anything this morning, while it worked fine literally six hours ago. tried updating to 26.06, no change, still 403 loops on every video.

**Comment by Saint8252** [comment]
> This may be ad-related because if I VPN through Albania, everything works.

Pretty sure mine worked on vpn also no issues. I tried many dns options and that didn't help. 

Does anyone know what domains the app is using to source the videos? If I need to use vpn it's fine but rather only use it for this app and set vpn to domain based. Other streaming apps don't like it sometimes.

**Comment by jmhg92** [comment]
Having 403 error loop on every video since yesterday night, even before updating to 26.06.

I'm on a Sony TV with Android OS 10, no VPN or anything else whatsoever.

**Comment by kemoxa** [comment]
I'm seeing the same issue starting yesterday. I thought it was caused by my country blocking the app somehow, so I used Adguard to set the DNS resolver to Google DNS which sometimes allow me to watch short videos usually just a few minutes long, but it still gives the 403 error most of the time. And for long videos it just asks me to sign in, not playing the video.

It seems to work better for stable than beta.

**Comment by ACR-Jeff** [comment]
I can confirm the latest beta works only with a VPN connected to a connection outside of the US. Anything within the US doesn't work on my end.

**Comment by Saint8252** [comment]
> I can confirm the latest beta works only with a VPN connected to a connection outside of the US. Anything within the US doesn't work on my end.

Same on my end. VPN no go either unless out of USA

**Comment by kabaww** [comment]
Also encountering this bug on Beta 26.06

The bug appeared after watching a few videos on my main YT account. Error 403 just keeps looping even when letting it fix itself for a minute.

However, switching to another account (same email) appears to work and I have never gotten the 403 error on the new account yet.

Hopefully this isn't Google timing out accounts and IPs for rejecting ad requests, something that OG Vanced tried to combat by pushing updates every week.

**Comment by yuliskov** [comment]
@kabaww can you check the bug with this option enabled Settings/Player/Dev. options/Buffering fix

**Comment by kabaww** [comment]
> [@kabaww](https://github.com/kabaww) can you check the bug with this option enabled Settings/Player/Dev. options/Buffering fix

After a few videos, the second account also had the 403 issue.

Enabling the buffering fix does not seem to fix the issue. Tried it on both accounts with app restarts in between.

Also tried to delete app data and log in again but the issue still persists.

**Comment by ACR-Jeff** [comment]
I had the buffer fix on so I disabled it, Same error loop, I then decided to change networks, Same issue, I found disabling sponsor block fixed it, Yet you know what that means.

**Comment by kabaww** [comment]
Interesting. I had SponsorBlock enabled but the video I was watching did not have any segments on it.

One thing I forgot to mention was that after switching accounts, 1 video played fine until the end. But the next video, it played fine at first but then it cut off in the middle of the playback and proceeded to do the error loop. Both videos had no sponsorblock segments with buffering fix turned off.

After restarting and clearing data again, I could play other videos just fine but the video that got cut off, I could no longer play.

Very weird

**Comment by ACR-Jeff** [comment]
> Interesting. I had SponsorBlock enabled but the video I was watching did not have any segments on it.
> 
> One thing I forgot to mention was that after switching accounts, 1 video played fine until the end. But the next video, it played fine at first but then it cut off in the middle of the playback and proceeded to do the error loop. Both videos had no sponsorblock segments with buffering fix turned off.
> 
> After restarting and clearing data again, I could play other videos just fine but the video that got cut off, I could no longer fully play through. I am able to seek back through the buffered parts of the video, but can no longer progress beyond the point where the error occurred.
> 
> Very weird

Well I guess I was incorrect on the sponsorblock, It worked on one video. Then started the error loop again. This is very weird indeed.

**Comment by Ralphie32** [comment]
I don't think this is just a Smart tube problem. I am trying to watch videos on the youtube app and within seconds of starting every video pops up with "something went wrong" and a qr code. I factory reset my box but that made no difference and I cant play any videos with Smart Tube. It just throws an error 403 unknown source code for everything

**Comment by sausagedogsalad** [comment]
Having the same issue on shield running beta 26.06 from Australia (with and without VPN). Issue started yesterday on previous beta and continued on 26.06. 

Turned off sponsor block and 1 video worked, then got continuous errors. Then a few videos randomly worked and now back to continuous cycling of the unknown source error 403.

**Comment by RealTwo12** [comment]
Same issue here on beta 26.06. It just continues to loop 403 error like everybody else but doesn't happen on every video, but still quite frequent.

So I tried to play videos on the actual YouTube tv app and I get an error saying something went wrong with a qr code. So it seems like an account related issue.

However when playing on revanced mobile, everything works fine and as intended, so it might be a YouTube tv issue?

**Comment by ppavacic** [comment]
> Same issue here on beta 26.06. It just continues to loop 403 error like everybody else but doesn't happen on every video, but still quite frequent.
> 
> So I tried to play videos on the actual YouTube tv app and I get an error saying something went wrong with a qr code. So it seems like an account related issue.
> 
> However when playing on revanced mobile, everything works fine and as intended, so it might be a YouTube tv issue?

I have come to the same conclusion. After error appears in the SmartTube app it also appears in the official YouTube app. I had that problem yesterday. To me sometimrs it appears as if its IP related and sometimes as if it is account related. It happens less often when using SmartTube without bring logged in.

**Comment by ACR-Jeff** [comment]
I am having similar issues with FreeTube, The only thing that's worked for me is using a previous version I had installed as a backup SmartTube v25.08 Stable, I didn't update it because it's always worked, And it's still working without the errors on my end.

**Comment by yuliskov** [comment]
Published the beta with the latest fixes.
https://github.com/yuliskov/SmartTube/releases/tag/26.07

**Comment by SkyNinja** [comment]
This seems to be a deliberate block from YouTube, as in my case it happens in both SmartTube and the official app, but only on devices with SmartTube installed.

**Comment by ppavacic** [comment]
> Published the beta with the latest fixes. https://github.com/yuliskov/SmartTube/releases/tag/26.07

Doesnt even load the video now 😞

**Comment by RealTwo12** [comment]
> > Published the beta with the latest fixes. https://github.com/yuliskov/SmartTube/releases/tag/26.07
> 
> Doesnt even load the video now 😞

Yeah same the video doesn't load I thought it was just me lmao

**Comment by kabaww** [comment]
> This seems to be a deliberate block from YouTube, as in my case it happens in both SmartTube and the official app, but only on devices with SmartTube installed.
> 
> Not IP related as other devices work, and not account related because it blocks viewing from every account on the affected devices. Seems to be a device ban.
> 
> Update: New beta causes a loading loop with no error.

I was able to watch videos on the official app tho while 'banned' from SmartTube. 

Sure smells like YT is banning devices at the very least. 
ReVanced tried the spoofing route and it caused even more problems but they kept the patch as optional.
NewPipe has implemented PO token generation and it looks like it worked for them. We already have this I believe but the problem still persists.

TeamNewPipe/NewPipe#11955

**Comment by kemoxa** [comment]
In beta 26.06, I can watch any video by waiting a few minutes while the error keeps running. It eventually plays but the wait time isn't consistent.
Sometimes after getting a video to play, I can play another video immediately but not always.

**Comment by Chebulex** [comment]
Currently on 26.09 on a Google Chromecast. Same 403 issue. Video doesn't start, infinite reloading with the 403 toast appearing.

**Comment by Saint8252** [comment]
> Currently on 26.09 on a Google Chromecast. Same 403 issue. Video doesn't start, infinite reloading with the 403 toast appearing.

Same on android emulator

**Comment by ACR-Jeff** [comment]
> This seems to be a deliberate block from YouTube, as in my case it happens in both SmartTube and the official app, but only on devices with SmartTube installed.
> 
> Not IP related as other devices work, and not account related because it blocks viewing from every account on the affected devices. Seems to be a device ban.
> 
> Update: New beta causes a loading loop with no error.

I don't think it's a device ban, If that was the case my device that has this issue with the newest beta's would also have it on smarttube v25.08 stable, Yet it hasn't and v25.08 stable is running strong.

**Comment by ACR-Jeff** [comment]
> > This seems to be a deliberate block from YouTube, as in my case it happens in both SmartTube and the official app, but only on devices with SmartTube installed.
> > Not IP related as other devices work, and not account related because it blocks viewing from every account on the affected devices. Seems to be a device ban.
> > Update: New beta causes a loading loop with no error.
> 
> I was able to watch videos on the official app tho while 'banned' from SmartTube.
> 
> Sure smells like YT is banning devices at the very least. ReVanced tried the spoofing route and it caused even more problems but they kept the patch as optional. NewPipe has implemented PO token generation and it looks like it worked for them. We already have this I believe but the problem still persists.
> 
> [TeamNewPipe/NewPipe#11955](https://github.com/TeamNewPipe/NewPipe/pull/11955)

I don't think it's a device ban, If that was the case my device that has this issue with the newest beta's would also have it on SmartTube v25.08 stable, Yet it hasn't and v25.08 stable is running strong.

**Comment by aksskl** [comment]
This 403 issue keeps coming up every so often while using the last few beta releases on a nvidia shield pro. I've been on 26.06 since it was released and just updated to 26.09. 26.09 seems to work but I've only been using it for a few minutes.

Whenever the 403 issue starts to occur I switch over to the stable release 25.24 and it goes away. Maybe it's a coincidence but so far, in my experience, if I switch back to the beta release after using the stable release for long enough the 403 issue will have subsided.

Ultimately the 403 issue goes away if I just wait or let the video buffer for a minute or two.

**Comment by Saint8252** [comment]
> > > This seems to be a deliberate block from YouTube, as in my case it happens in both SmartTube and the official app, but only on devices with SmartTube installed.
> > > Not IP related as other devices work, and not account related because it blocks viewing from every account on the affected devices. Seems to be a device ban.
> > > Update: New beta causes a loading loop with no error.
> > 
> > 
> > I was able to watch videos on the official app tho while 'banned' from SmartTube.
> > Sure smells like YT is banning devices at the very least. ReVanced tried the spoofing route and it caused even more problems but they kept the patch as optional. NewPipe has implemented PO token generation and it looks like it worked for them. We already have this I believe but the problem still persists.
> > [TeamNewPipe/NewPipe#11955](https://github.com/TeamNewPipe/NewPipe/pull/11955)
> 
> I don't think it's a device ban, If that was the case my device that has this issue with the newest beta's would also have it on SmartTube v25.08 stable, Yet it hasn't and v25.08 stable is running strong.

I just tried 25.08 stable and same 403 error

**Comment by yuliskov** [comment]
Published 26.10

**Comment by Saint8252** [comment]
> Published 26.10

Most videos work so far after a couple attempts of it applying fix. For some reason bluey videos from the offical bluey channel won't ever play.

**Comment by Vitosal-2024** [comment]
Hi there,

First wanted to say thank you for the all hard work. I appreciate it immensely. 

Second, I've got the 403 loop bug on my Android Top box as well. (V 26.10).

It was working yesterday for me yesterday and I didn't check it before I updated to the new version tonight. 

Mibox4
Android V9

If there is anything else you might need from my device to help with the issue please let me know.

**Comment by ACR-Jeff** [comment]
Here is a logcat if this helps

[SmartTube_beta-logcat.txt](https://github.com/user-attachments/files/18807446/SmartTube_beta-logcat.txt)

**Comment by paulzuri** [comment]
currently having this issue on 26.11 beta

**Comment by Saint8252** [comment]
> currently having this issue on 26.11 beta

Same. Lots of memory overload errors and video studdering, then halting.

**Comment by ACR-Jeff** [comment]
Starting to have this issue on previous release v25.08 Stable. It's surely caused by YT's side if it's hitting even older versions.

**Comment by gcogger** [comment]
Definitely an issue on the YouTube side. I was having major problems yesterday with multiple versions of SmartTube, ended up on 26.09. I found that, if I played a video on normal YouTube (with ads) then went back to SmartTube, it would work for a video or two, then get stuck in the endless 403 loop.
This morning, v26.09 is working fine. No changes on my side, but I haven't seen any errors all morning.

**Comment by NotoriousNico** [comment]
I'm on 26.11 Stable and still experience this issue.

**Comment by magster2** [comment]
I rolled back from 26.12 to 25 87 because 26.11 didn't work at all, the 403 error came up for all videos. After installing 25.87 the issue was still there for a few hours and now it has disappeared. All the videos are playing with no issues. I am using Xiaomi mi box with Android 11

**Comment by Saint8252** [comment]
26.11 beta been working today so far.

**Comment by jb89728** [comment]
Add to Playlist working for anyone with latest release?

**Comment by kabaww** [comment]
Tested Beta 26.11 just now and it is still working after a couple of videos. 403 error pops up every now and then but it fixes itself. 

Looks like the cache fix is working! Will report if it gets stuck in a loop again.

**Comment by Vitosal-2024** [comment]
Working on my top box as well. Appreciate it. Thought I was going to scream because of the YouTube ads. 

Lol. You never fully appreciate something until you lose it.

**Comment by ACR-Jeff** [comment]
Just updated to the latest v26.11 Beta, Playing some videos seems to work, Getting the 403 error popup only once or twice and then the video plays, Crossing my fingers that it continues working.

Thank you for all you do for us, Very much appreciated.

**Comment by magster2** [comment]
> I rolled back from 26.11 to 25 87 because 26.11 didn't work at all, the 403 error came up for all videos. After installing 25.87 the sign-in error issue was still there (for some videos) for a few hours and now it has disappeared. All the videos are playing with no issues now. I am using Xiaomi mi box with Android 11

I spoke too soon, the problem is now back. On the 25.87 stable version I am getting the sign in error for some videos. On the beta 26.09 I keep getting the 403 error that loops continiously and the video doesn't get played

**Comment by CaseyBlackburn** [comment]
I'm currently able to use v26.11 successfully on my Amazon FireStick 4K. However, my "History" only seems to show me the last few videos I've been able to play on this device on this build. So mostly good.

However, this isn't my normal usage, and I understand I'm kind of an edge case on this. I normally run with (*.)youtube.com and (*.)googlevideo.com redirected through a vpn to a personal dedicated server in a datacenter to bypass some throttling my ISP does on streaming media. When I have my setup running this way, SmartTube gets stuck in the 403 error loop. (On my computer the YouTube webpage and everything still function fine) This previously was working in v26.09 (and prior) until it stopped working. So possibly the presence of a datacenter/non-residential IP could be one of the causes of 403 errors in SmartTube's implementation.

**Comment by ACR-Jeff** [comment]
I've been playing videos on the latest v26.11 Beta for the last few hours, The only video that showed a 403 error for me was the very first video I played (Prior to restarting my device), So far after a restart of my device every video has played straight away and played well on my end.

**Comment by bbeef38** [comment]
Still got issue, reboot clear cache does not fix. Also getting issue with legit youtube..  Only web based youtube working for me currently.

**Comment by ppavacic** [comment]
> Still got issue, reboot clear cache does not fix. Also getting issue with legit youtube.. Only web based youtube working for me currently.

Version? Have you enabled fix#1 and fix#2 in Settings -> player?

**Comment by ACR-Jeff** [comment]
I've been using v26.11 Beta all day and I haven't seen any further 403 errors, I am going to close this issue, Thank you very much.

**Comment by arun2118** [comment]
> > Still got issue, reboot clear cache does not fix. Also getting issue with legit youtube.. Only web based youtube working for me currently.
> 
> Version? Have you enabled fix#1 and fix#2 in Settings -> player?

The frame drop fix? Developer options?

**Comment by adz7** [comment]
Why has it broken standard YouTube app as well though?  If I try to play anything on my Sony TV (Google TV) it's doing the same thing? If I switch YT account to one that has not been connected QR code to SmartTube then it works fine.  Seems to be an issue related to the account used with SmartTube.

STN v26.11 (issues started immediately after this update).
Nvidia Shield
Clear Cache, Clear Data (Lost all of my settings)..
Rebooted, no difference. Only thing I haven't tried is complete uninstall/reinstall.

Get 403 Error on every video at 59seconds - wait for it to "Apply the fix" but doesn't work, just keeps trying to fix and looping.

**Comment by DocenciaLibre** [comment]
> Sign out, sign back in appears to have resolved it. Nvidia Shield Pro SmartTube v26.11

The issue is not solved here in spite of signing out and back in. Using v26.26 on a fire tv device.

**Comment by Chrismucer** [comment]
I have sign out but it keeps crashing on fire tv stick 4k.

**Comment by Fire-** [comment]
> Sign out, sign back in appears to have resolved it. Nvidia Shield Pro SmartTube v26.11

I can't even try this because the sign in flow no longer lets me select my brand account like it did when I originally set up the app.

**Comment by pman92** [comment]
Same issue for me. Just updated to 26.27. Videos play for 30 seconds and then I get a 403. Fix is applied and I get another 30 seconds or so and it does it again.

**Comment by bbeef38** [comment]
I installed the beta and then applied the various fixes in settings, developer.  so far seems OK.. I'm Nvidia shield.

**Comment by Centavito** [comment]
> I installed the beta and then applied the various fixes in settings, developer. so far seems OK.. I'm Nvidia shield.

Could you please share which setting fixes you applied?

I've been having the 403 issue for several days. Updated to beta, updated to 26.27.
Changing the buffer to maximum helped a bit, but for some reason the buffer fails to continue to move along with the video. 
The playback will catch up to the buffer limit, then the 403 error will pup up, after a bit it'll start to buffer and play again. This will continue to happen every time the playback catches up to the stalled buffer limit.

**Comment by magster2** [comment]
> > I installed the beta and then applied the various fixes in settings, developer. so far seems OK.. I'm Nvidia shield.
> 
> Could you please share which setting fixes you applied?
> 
> I've been having the 403 issue for several days. Updated to beta, updated to 26.27. Changing the buffer to maximum helped a bit, but for some reason the buffer fails to continue to move along with the video. The playback will catch up to the buffer limit, then the 403 error will pup up, after a bit it'll start to buffer and play again. This will continue to happen every time the playback catches up to the stalled buffer limit.
> 
> PS: this is my first time posting about this app, which I just discovered a couple of months ago. I want to take the opportunity to say how great it has been. It has been a game-changer. Awesome app. I use it on my FireStick.

I am using Beta 26.27,I went to settings--player-developer options and checked "playback buffering fix", it seemed to have resolved the problem

**Comment by Chrismucer** [comment]
Yesterday the videos in the official app didn't work for me either. I live in Spain, maybe it's LaLiga's blocking of Cloudflare? Today I can watch the videos that I couldn't yesterday and there is no football....

**Comment by V4ler1an** [comment]
NVidia Shield, never had this 403 error much before but since the 26.11 update was installed a few days ago it's been almost constant. Every video. Here's the thing though, it *only* does it when i'm on my VPN! If I bypass it, all fine. Turn it back on, it returns. For me at least, there is definitely something going on with network connections through VPN. Anyone else found this?

**Comment by bbeef38** [comment]
![Image](https://github.com/user-attachments/assets/28e90877-27d4-496d-9551-b06bad3ef3e9)
![Image](https://github.com/user-attachments/assets/d2f1d861-47d2-429c-a1cf-2a12674b38e6)
![Image](https://github.com/user-attachments/assets/960616dc-207a-4fca-9c3e-d1b4fc6fca5e)
![Image](https://github.com/user-attachments/assets/73dc17bc-31bc-42a4-be2a-a03ef1d776d0)
![Image](https://github.com/user-attachments/assets/4f9b5348-1aab-4bde-8316-d71edf3cc16f)
![Image](https://github.com/user-attachments/assets/f97f1830-27d6-477a-8450-836fa0c66383)

**Comment by yuliskov** [comment]
Prepared another build addressed 403 error but it's VERY UNSTABLE. Try it only if videos are unplayable.
https://github.com/yuliskov/SmartTube/releases/download/latest/SmartTube_beta_testing.apk

**Comment by b8hoven** [comment]
> > > I installed the beta and then applied the various fixes in settings, developer. so far seems OK.. I'm Nvidia shield.
> > 
> > 
> > Could you please share which setting fixes you applied?
> > I've been having the 403 issue for several days. Updated to beta, updated to 26.27. Changing the buffer to maximum helped a bit, but for some reason the buffer fails to continue to move along with the video. The playback will catch up to the buffer limit, then the 403 error will pup up, after a bit it'll start to buffer and play again. This will continue to happen every time the playback catches up to the stalled buffer limit.
> > PS: this is my first time posting about this app, which I just discovered a couple of months ago. I want to take the opportunity to say how great it has been. It has been a game-changer. Awesome app. I use it on my FireStick.
> 
> I am using Beta 26.27,I went to settings--player-developer options and checked "playback buffering fix", it seemed to have resolved the problem

This stopped the constant playback fix loop for me on the stable build. It applied the fix once and then the video worked as normal

**Comment by MirahImage** [comment]
I fixed it just by clearing the cache

**Comment by Hyss** [comment]
I have a 403 error on both my Nvidia shield and my chromecast HD. This has been happening since at least 9am GMT.

I have cleared the cache and restarted the devices, but not helping. I assume YouTube has changed something.

**Comment by Kandelai** [comment]
Smartube 403 Error on my Firestick. Cleared cache, changed engines, rebooted, and still getting 403.

**Comment by modo1302** [comment]
same here! updated to the latest stable version did not solve the issue. cache cleared, restart done - still no luck.

**Comment by girkers** [comment]
I have cleared the cache and done all the developer settings and I too get the dreaded 403 error and can't play any videos.

**Comment by dcquence** [comment]
I have done a full uninstall/wipe and reinstall with the most recent beta on my Dune HD 4K and Shield but both get the error. Live streams are the only thing that will play

**Comment by jb89728** [comment]
Same here. Live works. I played a couple Live videos and then went back to a Non-Live video and it worked. Odd

**Comment by Frodo69** [comment]
Both Smart Tube and Beya are throwing 403.  But, most live seem to work.

**Comment by cobeypass** [comment]
updated 26.95 it's work

**Comment by nobiman** [comment]
Updated to 29.95, still error 403.
(Android-TV 11, Kernel 4.19.182-ab2990 on Philips, Location: Germany)

**Comment by bexbasil** [comment]
Update to 26.95 and it'll work again

**Comment by celeritax** [comment]
Tried both 26.95 and beta and none of them works. 403 error on both. Also applied the dev option fix, still same issue.

**Comment by Frodo69** [comment]
Problems went away after ignoring SmartTube for 5 hours. Realized problem appeared immediately after fire stick forced an upgrade.

**Comment by digitall12** [comment]
Here the same : 26.95 give me an 403 response code. Inspite the update 403fix2

**Comment by Sandt85** [comment]
Installed v3 fix .. but issue persists.

**Comment by Frodo69** [comment]
I installed today's beta, 403 error, about 2 hoirs. Then ok. Seems to be Smart tube and Firestick updates, that cause a short term 403 errors of a few hours.

**Comment by Sandt85** [comment]
installed fix4 . Now it's working great 💀

**Comment by Sandt85** [comment]
Also I have disabled auto volume adjustment as it reduces volume too much even after  raising volume to 300% in settings. .just mentioning in case someone struggling with lower volume .
