### ISSUE TITLE
[BUG]: "unknown source error Response code:403" it's in a loop

### ISSUE THREAD

**Issue by Abhiram-who** [yuliskov/SmartTube#4462]
### Checklist

- [x] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [x] This issue contains only one bug.

### Affected version

26.75

### Device Type

Smart TV/Box

### Affected Android

Android TV

### Steps to reproduce the bug

Just play any video, it loads but this shows up

**Comment by kkrusher741** [comment]
Same issue.

**Comment by dontwantonebutneedone** [comment]
Same thing. Never comes out of it. I happened to clear the cache on it just before it happened. Weird thing is I have a second tv with smarttube on it that still works fine, albeit on an old (2015) sony android tv. The shield won't play anything even after a reboot. The old tv will even play the videos from History that the Shield loops with a 403 error.

I removed the high bitrate video option, set it to all 3 of the network engine options, and changed the DNS to IPV4 Only. Same result. It's as though the tv has a token that's letting it play videos but the shield lost its and can't find its way back.

**Comment by ReK42** [comment]
I had the same issue. Clearing both cache and all data for the app fixed it.

**Comment by Artemis-the-gr8** [comment]
I'm having the same issue. Clearing both cache and all data for the app seemed to fix it, but as soon as I imported my backed up settings, it went back to the infinite 403 loop.

**Comment by Abhiram-who** [comment]
Fixed it, clear cashe and data

**Comment by bigshiny90** [comment]
Had the same issue. Clearing data/cache allowed me to play vids again. 

In my case, restoring my backup reintroduces the problem.

Instead, I had to sign in again from scratch. (Two accounts)  This seemed to fix the issue.

**Comment by TheColdOne** [comment]
This started for me late yesterday afternoon (PDT).

I reverted back to 26.47 (Stable) and that worked for me. I'm going to leave my beta install alone (for now) and see if an update fixes it instead of wiping.

**Comment by MirahImage** [comment]
I fixed it just by clearing the cache

**Comment by dontwantonebutneedone** [comment]
> Same thing. Never comes out of it. I happened to clear the cache on it just before it happened. Weird thing is I have a second tv with smarttube on it that still works fine, albeit on an old (2015) sony android tv. The shield won't play anything even after a reboot. The old tv will even play the videos from History that the Shield loops with a 403 error.
> 
> I removed the high bitrate video option, set it to all 3 of the network engine options, and changed the DNS to IPV4 Only. Same result. It's as though the tv has a token that's letting it play videos but the shield lost its and can't find its way back.

After seeing the replies, I deleted the app data and relogged in, set the settings back manually to where they were, and the app played videos throughout the process.

So for me, clearing the cache made the problem start and deleting the data made it stop. Or it was a completely coincidental thing that it stopped working right after I cleared the cache.

**Comment by DDSK15** [comment]
Nothing is working for me at the moment. I tried both clearing the cache and deleting data, but no joy

**Comment by deukmolee** [comment]
I think there's a problem with 26.80. I need to roll back to a previous version.

**Comment by FuryriderX** [comment]
Rolling back to 26.75 beta and restoring my data seems to be working for me.

**Comment by vitich** [comment]
26.75 worked for several weeks, but stopped working today...

**Comment by Innofusion-Charon** [comment]
where to clear cache and data

**Comment by Ravn73** [comment]
Same problem. Its in a 403 loop. Cleared Cache and other stuff. Didnt Backup anything. Logged in. And its still looping. Using a Firestick 4k.

**Comment by bigshiny90** [comment]
I previously fixed this issue (see earlier post in this thread), but now the issue has returned and I cannot fix it.

My previous fix was to “clear data” then re-connect my accounts. (Clear cache didn’t work. Clear data and then restore from backup didn’t work.)

Now, nothing works. Smart tube is non-functional for now.

Btw…. Android TV OS 12 build STT2.230310.002

**Comment by bmh67wa** [comment]
Unknown source error
Response code: 403...

Everything worked fine last night. Woke up this morning and every video throws this error code and loops it over and over.

**Comment by aienpme** [comment]
Unknown Source Error
Response Code: 403

Same issue here, installed it freshly on a FireTV Stick. Seems to work fine on my Chromecast with GoogleTV. Really weird.

**Comment by zosoleary** [comment]
Same issue here on both Fire Cube and ONN Pro. Just started today

**Comment by Onijai** [comment]
Same on Shield TV. Clearing cache didn't do anything.

**Comment by Shasdo** [comment]
Same on Shield TV.

Cleared cache and data to no success.

Stuck at : 
Unknown source error
Response code: 403
Don't close the player, applying fix (approximately translated from french.)

**Comment by cubilas** [comment]
Videos were working great this morning, Amazon Firestick, now 403 on every video.

Loops at :
Unknown source error
Response code: 403
Don't close the player, applying fix

(p.s. Thanks for *the best* YouTube experience with SmartTube!!)

**Comment by Tenshinen** [comment]
Same issue for me. Reinstalls, clearing cache, beta versions, nothing has worked so far

**Comment by Loidauk** [comment]
Same error here on a Nvidia Shield.
Discovered it after I cleared all data and set it up anew.
It's the same even after reinstall of version 26.75.

**Comment by aienpme** [comment]
Could anybody using a FireTV Stick confirm if the YouTube app is also not working for them (the normal app) alongside SmartTube?

**Comment by glang25** [comment]
Same issue as others above. I’ve tried clearing cache and deleting data, and reinstalling stable and beta. I’m just letting it loop with the 403 issue now. This is on an Android TV. It started right after I initially cleared cache. Beta is still working on a fire stick TV I have it on.

**Comment by elle8che** [comment]
> Could anybody using a FireTV Stick confirm if the YouTube app is also not working for them (the normal app) alongside SmartTube?

Fire Stick here. This issue just appeared in the last few minutes, and I am in a loop. I exited, cleared the cache, rebooted the fire stick. The issue remains.

**Comment by StormieFN** [comment]
26.75 reinstall and a user 26.47 stable suggest. Nothing worked

**Comment by StormieFN** [comment]
> Same issue as others above. I’ve tried clearing cache and deleting data, and reinstalling stable and beta. I’m just letting it loop with the 403 issue now. This is on an Android TV. It started right after I initially cleared cache. Beta is still working on a fire stick TV I have it on.


On 46.75 beta?

**Comment by StormieFN** [comment]
So is this Google YouTube blocklisting our client from accessing videos now again and again?

**Comment by YousufR47** [comment]
Same here, im using 26.75 and it seems to not be working on my Firestick HD. I trired clearing cache and have reinstalled the app twice. Once with kutt.it/stn_stable and the downloader code 28544.

**Comment by axpmonkey** [comment]
Just started as well. Uninstalled and re-installed both latest beta and stable. Neither works, both just loop.

**Comment by LeeRoyManea** [comment]
Same here on shield.  Uninstalled and reinstalled completely beta + stable.

Thank you Smart Tube Team for the great value you provide.

I should look for a donation link. The money spent here would be better spent than on youtube.

**Comment by Ezelboy1000** [comment]
Stuck in a loop here as well on app version 26.75 (stable) on the Shield Pro. Clearing cache did not fix the issue for me.

**Comment by stromdriver** [comment]
same on shield pro 19 latest stable
trying to let it run like others have to see if it comes around

**Comment by wallflower1965** [comment]
Same problem on Ematic Jetstream AGT419, last night it stopped working, this morning it worked again and now again: Response Code 403.  I have cleared cache and data and the situation has not improved. However no issues on Sony Android TV KD-65XE9005.

**Comment by jack-mehoff-u-jerk** [comment]
Same. 26.75. Shield TV (two different boxes). clear cache, clear data...still does not work, infinite 403 loop starting some time in the last 12 hours.  tried latest beta too. tried reinstall without login to youtube, does not work. re-login does not work. backup and restore does not work. thanks for all the hard work, has been a Godsend for me. this app is better (IMO) even than the stock youtube app, even paid subscription.

**Comment by cubilas** [comment]
Working again on Firestick HD! Northern USA

**Comment by wallflower1965** [comment]
> Same problem on Ematic Jetstream AGT419, last night it stopped working, this morning it worked again and now again: Response Code 403. I have cleared cache and data and the situation has not improved. However no issues on Sony Android TV KD-65XE9005. Anyway thank you very much to the Smart Tube team, their work is heroic. A donation would be the least I can do. These waves of Youtube ads make watching videos unfeasible

Sony Android TV KD-65XE9005 has also stopped working, same isuue.

**Comment by elle8che** [comment]
Working well with the updated version -- thank you very much to the developers. FYI, videos you clicked on yesterday that resulted in the 403 error are counted as viewed, and are in your history.

**Comment by wallflower1965** [comment]
Update 26.75 worked perfectly on both, Ematic Jetstream AGT419 and sony Android TV KD-65XE9005. Thank you so much.

**Comment by aristodemos2008** [comment]
I still have this issue even after installing Beta 26.99

**Comment by stromdriver** [comment]
issue was resolved now seems to be back again today

**Comment by djtierta** [comment]
26.96 on Shield TV still not working after clearing the cache and data.  Endless 403 loop.

**Comment by ACR-Jeff** [comment]
Hello. Are you still experiencing this issue with the current latest version?

**Comment by djtierta** [comment]
> Hello. Are you still experiencing this issue with the current latest version?

No problem on version 30.90.

**Comment by ACR-Jeff** [comment]
@djtierta Thank you for the update.

Marking as Resolved. Due to a high volume of stale issues prior to current releases. It is possible this issue has been resolved by a current version. 

Please feel free to resubmit your issue if you believe it has not been appropriately dealt with. and tag this issue in the Additional Information section.
