### ISSUE TITLE
[BUG]: Channels with "Active" Live Stream's do not conain any videos other than the "Live Stream"

### ISSUE THREAD

**Issue by optio50** [yuliskov/SmartTube#4465]
### Checklist

- [x] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [x] This issue contains only one bug.

### Affected version

26.80

### Device Type

Smart TV/Box

### Affected Android

Android TV v12

### Steps to reproduce the bug

Go to a subscribed channel that has an "Active" Live Stream.
Only the live stream shows up, no other videos.
If you long press and bring up the context menu, If you select "Open Channel" the videos are there.

### Actual behavior

Go to a subscribed channel that has an "Active" Live Stream.
Only the live stream shows up, no other videos.
If you long press and bring up the context menu, select "Open Channel" the videos are there.

Sample Channels
[NASA Space light Now](https://www.youtube.com/@NASASpaceflight/videos)
[Space Flight Now](https://www.youtube.com/@SpaceflightNowVideo/videos)
[What About It!](https://www.youtube.com/@Whataboutit/videos)
[Lab Padre space](https://www.youtube.com/@LabPadre/videos)
[BBC Earth](https://www.youtube.com/@bbcearth/videos)

### Additional information

N/A

**Comment by joao-matos** [comment]
I have this issue too. If a subscribed channel has a live stream, those channel videos do not appear in the channels or subscriptions browser. The channel video list only appear if browsed through the general search browser.
Smarttube 27.99 fresh first install yesterday.
Android TV11

**Comment by joao-matos** [comment]
The behaviour is fixed if a signed in account is used

**Comment by ACR-Jeff** [comment]
Hello. Are you still experiencing this issue with the current latest version?

**Comment by optio50** [comment]
@ACR-Jeff  Yes this is still an issue with 30.90 beta. Anonymous account (as in, not signed in)
Left side menu ---> Channels ----> "any channel that has a live stream" = No videos (only live stream).
I suspect this issue also prevents these videos from showing up in the video subscriptions. I never see new videos (in subscriptions) from a channel that has an active live stream.

**Comment by ACR-Jeff** [comment]
@optio50 Thank you for your update, Ok, I've been messing with the Anonymous accounts as well and I've noticed some similar issues, I will leave this opened and change the title accordingly.
