### ISSUE TITLE
[BUG]: Playlists videos not displaying after Changelog update, prior to release 28.49.

### ISSUE THREAD

**Issue by Annathin** [yuliskov/SmartTube#4704]
### Checklist

- [x] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [x] This issue contains only one bug.

### Affected version

28.49

### Device Type

Smart TV/Box / Amazon FireTV Cube

### Affected Android

Android TV 11

### Steps to reproduce the bug

SmartTube beta
Channel lists - Scroll down to Next Level Soul Podcast 
Videos list is blank
Click on Channel name and various categories are listed
Scroll down to Created Playlists over to Next Level Soul Podcast, click and screen is blank
Click another Playlist, ex Near Death Experiences, that is suppose to have 125 videos, click it and screen is blank. 
No videos will display to pick to watch. Just a blank screen. 
This has been is the 3rd update and problem is still occurring.
If I go to YouTube, the videos all display like normal.

![Image](https://github.com/user-attachments/assets/7aeb447a-0553-43a5-852f-f27e6830b539)

### Actual behavior

No playlist videos load for channel
This is the only channel that is not loading properly for me.

**Comment by beefjerky9** [comment]
I am also seeing this on my ShieldTV box with the latest release version (not beta). Specifically, the Ryan Trahan channel.

**Comment by Annathin** [comment]
Installed new update 28.50 on Amazon FireTV Cube. Cycled through channels list a couple of times.  Each time for Next Level Soul Podcast, one video was appearing. Went into channel and under....example...Created Playlists, Soul's Journey that is suppose to have 127 videos, it was empty. Matter of fact all Playlist are empty. There were a couple other categories that had 1 showing and next time it was empty. Now, 3rd and 4th time cycling through main channels list, Next Level Soul Podcast is once again blank. This is still the only channel in my list that is having this problem.

**Comment by Annathin** [comment]
Installed update 28.56. Still have same issue.

**Comment by dereckhall** [comment]
i rolled back to 27.99 Stable for now.

**Comment by roman-la** [comment]
can confirm, but its not only limited to the playlists, some channels are not showing at all (e.g. Ryan Trahan, as already mentioned by @beefjerky9). Only workaround for now is to start the videos on e.g. mobile device and then you can find then im the watched section.

**Comment by Annathin** [comment]
Updated to changelog update 28.75. Problem with Next Level Soul Podcast not loading is now fixed! Thank you!!!

**Comment by beefjerky9** [comment]
> can confirm, but its not only limited to the playlists, some channels are not showing at all (e.g. Ryan Trahan, as already mentioned by [@beefjerky9](https://github.com/beefjerky9)). Only workaround for now is to start the videos on e.g. mobile device and then you can find then im the watched section.

This still happens with the newest 28.75 release. For me, I use the search to find "ryan trahan states," and it works well. And, since it saves my recent searches, it's convenient-ish. But, I would still love to have the problem fixed.

**Comment by hay** [comment]
Think this has been fixed with the 28.78 release (see also #4697).

**Comment by ACR-Jeff** [comment]
Closing as Duplicate. 

Please feel free to resubmit your issue if you believe it has not been appropriately dealt with. and tag this issue in the Additional Information section.
