### ISSUE TITLE
[BUG]: Watched videos on TV aren't synced with my video history in web or in the mobile app

### ISSUE THREAD

**Issue by LoonyBeLuna** [yuliskov/SmartTube#4809]
### Checklist

- [x] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [x] This issue contains only one bug.

### Affected version

28.78

### Device Type

Smart TV/Box

### Affected Android

FireTV

### Steps to reproduce the bug

Watch a video, see it's in the "recent watched videos" lust on the tv, then go to your phone and check your app or just YouTube.com in web and see the video is not listed.
Videos I add to "watch later" or which I have liked are synced to my "liked videos" but not my video history.
I also didn't play the videos incognito.

History on TV:
![Image](https://github.com/user-attachments/assets/7d1b2ac6-4e27-4dc0-9fa0-f1c766909288)

History on web/app:

![Image](https://github.com/user-attachments/assets/b650011c-a9d9-4bfa-8bd4-3aeb0bbed416)

You can see that many videos are missing like the documentary or world of warships or Americans got talent.

I often use my phone to comment on my last watched video.
Videos I liked are synced:

![Image](https://github.com/user-attachments/assets/a566398a-dd91-46c8-b97f-2cf66dac7c6c)

If the video is played incognito, it should not even get listed in my history on tv, but there is it listed.

I made now also a reverse test, I clicked a video on web and it's listed in my history on web but doesn't appear in the history on tv.

History on tv:

![Image](https://github.com/user-attachments/assets/d299c074-ddd5-4547-b6c8-781e1edde04e)

Playlist, where you see it in the liked videos:

![Image](https://github.com/user-attachments/assets/039ec7f3-2b58-4339-9e14-c34bb18650ba)

History on web:
![Image](https://github.com/user-attachments/assets/f9dee9ed-9d71-43d9-bb71-268f0314a3b2)

Notes for translation:
"Später ansehen" = watch later
"Videos, die ich mag" = Videos I like/ liked videos.

### Actual behavior

The view history is not shared between the TV and the mobile app or the YouTube website in both directions.

### Additional information

Fire TV stick 4k with newest Smarttu e version installed.
The bug is new, my last synced videos are from last Thursday , 31. July 2025.

**Comment by LoonyBeLuna** [comment]
Here you can see the last 2 videos on my TV on Thursday got also a grey/broken thumbnail:
![Image](https://github.com/user-attachments/assets/db8acbd4-373c-4b3c-ab92-13df253bfbcb)

Web/mobile:

![Image](https://github.com/user-attachments/assets/aa5dd3ff-1479-42dd-8779-ed15798395b0)

All videos there  beyond Thursday are clicked on my phone in quick research. (I don't really watch YouTube on my phone aside from tutorials for cooking or if I am building/repairing something and need help 😅)

**Comment by sherpajosh** [comment]
I am having the same issue too. History between other devices and SmartTube are not syncing.

**Comment by BigPeeper** [comment]
Also having this issue. Nothing I watch on smart tube is showing up on my phone or on web.

**Comment by asandhu3** [comment]
+1 Same issue on Shield Pro and Shield tube.

**Comment by clampy** [comment]
I have the same issue, and I think it is affecting suggestions on the app as well as my suggestions seem different between my phone/PC and STN. Likes and subscriptions seem to be syncing fine, but history does not.

History syncing is enabled in the app on STN and my google account has history syncing enabled for YT.

**Comment by illuvattarr** [comment]
+1 Also having this issye since the most recent smarttube update

**Comment by ram-sez** [comment]
this started on tues night for me. I have several yt accounts but this is only happening on 1 of them(the oldest OG account). Videos are not being noted as watched on the yt servers.

**Comment by LoonyBeLuna** [comment]
The app got an update, click on the start page on your settings button on your remote to open the side panel, check for updates. This is now fixed.

**Comment by josap97** [comment]
I'm on the latest 30.43 version on a Google TV streamer and still having this same issue. It also occasionally doesn't register watch progress on the TV app either.

**Comment by LoonyBeLuna** [comment]
Version 32.10 the bug is sadly back since the newest version.

**Comment by LoonyBeLuna** [comment]
It's now working again.
Can we close it or waiting for others?

**Comment by ACR-Jeff** [comment]
@LoonyBeLuna Thank you for the update.

**Marking as Resolved** 

After reading the issue. It appears this issue has been resolved. I'm now closing this issue. 

Please feel free to resubmit your issue if you believe it has not been appropriately dealt with. and tag this issue in the Additional Information section.

**Comment by LoonyBeLuna** [comment]
> [@LoonyBeLuna](https://github.com/LoonyBeLuna) Thank you for the update.
> 
> **Marking as Resolved**
> 
> After reading the issue. It appears this issue has been resolved. I'm now closing this issue.
> 
> Please feel free to resubmit your issue if you believe it has not been appropriately dealt with. and tag this issue in the Additional Information section.

The bug is sadly back 😢.
I can again not see my watch history on my phone being updated. Only when I like the video and check "videos I like".

**Comment by JustTooKrul** [comment]
Having the same thing occur and I was using an older version and then updated, same issue. Also, opening the YouTube app on mobile doesn't show the videos as watched either. Seems to have stopped being in sync on August 19th, 2026.

**Comment by Lentzeris** [comment]
I'm also experiencing this issue on version 32.10

- Watched videos appear in SmartTube's local history on my TV
- However, they do NOT sync to my YouTube history on mobile or web, or even to another instance of SmartTube.
- Likes and "Watch Later" videos are syncing correctly, which confirms my account connection is working
- History sync is enabled in SmartTube settings and my Google account has history tracking turned on

This started happening recently, matching the timeline others have mentioned (around mid-August 2026). I've tried restarting the app and re-authenticating my account, but neither helped.

Please let me know if you need any logs or additional details to help debug this.

**Comment by Fredator1** [comment]
Hello,
I have the same issue since some time.
The videos i watch in smartube on a tv don't show up in my history on other devices.

Yesterday i manuaily downloaded the last version, in case of, and started the google authentication process from the sart.

Same result, no history saved. All the things i watch in smartube are show unread on other youtube devices

**Comment by LoonyBeLuna** [comment]
On version 32.38 is the bug again fixed. [Got the update yesterday]
Let's see for how long 🫣.
