### ISSUE TITLE
[BUG]: Playlist section not sorting correctly

### ISSUE THREAD

**Issue by SonOfDiablo** [yuliskov/SmartTube#5005]
### Checklist

- [x] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [x] This issue contains only one bug.

### Affected version

29.83

### Device Type

Smart TV/Box

### Affected Android

Android TV 14

### Steps to reproduce the bug

1. Play something from a playlist
2. Go to Playlists section

### Actual behavior

Nothing seems to change

### Additional information

So I might just be remembering this wrong.
But I swear that the Playlists in the Playlist section would be ordered from last edited/played from Playlist first, after "Watch Later".

But now the order is "Watch Later", "Liked Videos" and then some seemingly random order of the rest of my created/saved Playlists.

Having it put the last interacted with Playlist at the top were super convenient because you could quickly get back to what you were watching without having to sift through some random order.

**Comment by ACR-Jeff** [comment]
Hello. Are you still experiencing this issue with the current latest version?

**Comment by SonOfDiablo** [comment]
> Hello. Are you still experiencing this issue with the current latest version?

Nope, it was fixed a few versions ago.

**Comment by vertexx** [comment]
I still have this problem. Both in the release version and in the latest beta. Playlists aren't sorted alphabetically. Both the website and the mobile app are sorted alphabetically. The SmartTube app doesn't have any option to sort playlists at all.

**Comment by ACR-Jeff** [comment]
@SonOfDiablo and @vertexx Thank you both for the updates,

@vertexx I've noticed this as well while reviewing another bug report, The alphabetical order isn't available, Since the option isn't available, This would be a feature request https://github.com/yuliskov/SmartTube/issues/4680

**Marking as Resolved** 

After reading the issue. It appears this issue has been resolved. I'm now closing this issue. 

Please feel free to resubmit your issue if you believe it has not been appropriately dealt with. and tag this issue in the Additional Information section.
