### ISSUE TITLE
[BUG]: Videos not marked as watched

### ISSUE THREAD

**Issue by karnavara** [yuliskov/SmartTube#5111]
### Checklist

- [x] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [x] This issue contains only one bug.

### Affected version

30.43

### Device Type

Smart TV/Box

### Affected Android

Android TV 11 (SHIELD Android TV 9.1.2)

### Steps to reproduce the bug

1. Watch any video till the end

---------- OR

1. Mark video as watched manually with context menu

### Actual behavior

1. Not marked as watched but shows roughly 25% progress
 
---------- OR

1. Not marked as watched but resets to last progress

### Additional information

I made sure that there are no existing issues for the current version so this is filed as new bug report for 30.43

**Comment by amphoterism** [comment]
Another annoying part of this bug is if you have it set to play videos in this playlist only, when it finishes the last video in the list, it will start the whole thing over since the first video is not marked as watched

**Comment by karnavara** [comment]
Logging out of the account and cleaning the cache will help for a few videos but then return to the buggy behaviour

**Comment by yisenliu** [comment]
same here

**Comment by Sarcas666** [comment]
Yep, quite annoying. Keeps coming back.

**Comment by karnavara** [comment]
Still persistent in latest updates, I wonder if it is a mistake that I created or is this being overlooked ?

**Comment by Section25** [comment]
The worst part of this bug is that most of the videos that I have watched are being recommended in Home as recommendations as if I need to finish watching them.

By the way, it's only about 10% of the progress bar for me which is in line with a previous bug.

**Comment by ItsEpicBeast** [comment]
Same issue, next shows as fully watched

**Comment by Norsagir** [comment]
Very annoying issue, especially when you activate the option to hide watched videos...
When you watch a video, progress bar is not 100% even if you reached the end of the video.
The option "mark as watched" is also not working.
And it seems that even if I watch the end of the video on Youtube Web, SmartTube is effectively hiding the video but not updating the progress bar...

**Comment by steros** [comment]
I reproduced the same on Youtube itself. It probably isn't even a SmartTube bug: https://github.com/yuliskov/SmartTube/issues/5240
(or at least only partially)

**Comment by Section25** [comment]
@steros It has been reported as a bug previously (maybe 4-6 months ago) and addressed in an update.

**Comment by karnavara** [comment]
would love to see this fixed, has a high priority in my eyes as most of us are going crazy :D

**Comment by karnavara** [comment]
Still happening in latest version , it got even worse , sometimes it even removes the already watched videos and resets them to 5/10 %

**Comment by steros** [comment]
Youtube fixed videos marked as watched. At least for me. Now watching videos marks them as watched again.
But I assume they implemented a new feature to prevent users marking as watched even though they haven't watched fully.
That's probably why it didn't work temporarily as they released it with a bug.

Either way, now I can't skip to 1 sec before the end of the video and then watch to the end to mark it as fully watched. It will only mark it as ~10% or so watched.
That's on Youtube itself, not with SmartTube.

**Comment by karnavara** [comment]
Nah still happens even when watching a video normal from start to end , afterwards it appeared as 10% watched..

To see this and the "mark as watched" feature fixed - would be a dream.

**Comment by Feature-requester-general** [comment]
I also still have this behavior on CCwGTV HD with the newest version (30.75). Very annoying!

**Comment by GitStudying** [comment]
Not sure why this is not solved. For sanity I rechecked a build I did to test a PR. The version is 30.25 and that does perfectly mark the watch history while the latest at least stable 30.75 does not work and only shows like the first minimum part that it has been started in a video.
I am quite sure it was working around 30.45 and down for me but of course the build ones are not recommended due to the malware/possible build tampering.
For now I continue on my own build as I can't take it that months of videos aren't marked as watched. It definitely is a client problem like this proves. I would think the maintainer/developer should relatively easily see where this goes wrong.

**Comment by karnavara** [comment]
> Not sure why this is not solved. For sanity I rechecked a build I did to test a PR. The version is 30.25 and that does perfectly mark the watch history while the latest at least stable 30.75 does not work and only shows like the first minimum part that it has been started in a video. I am quite sure it was working around 30.45 and down for me but of course the build ones are not recommended due to the malware/possible build tampering. For now I continue on my own build as I can't take it that months of videos aren't marked as watched. It definitely is a client problem like this proves. I would think the maintainer/developer should relatively easily see where this goes wrong.

Maybe this reply and additional infos can help him analyze it, we really need it I am stuck in a loop that I sometimes watch the videos I already watched (haha!)

**Comment by Getfree** [comment]
I'm on version 30.75. At this point I have already adapted to interpret the 10%-watched red-bar as if it was 100% watched because that's what it actually means. Very annoying indeed.
Would love to see this fixed!

**Comment by karnavara** [comment]
> I'm on version 30.75. At this point I have already adapted to interpret the 10%-watched red-bar as if it was 100% watched because that's what it actually means. Very annoying indeed. Would love to see this fixed!

Tried that too but sometimes its kinda fake , it shows as 10% watched (kinda 100%) but when you open it it resumes at any random % you basically stopped.

Its a massive mess :D

**Comment by karnavara** [comment]
30.82 seems to have fixed the "marked as watched" issue when watching it normally to 100% - thanks for that! 

However the clicking on a video and manually mark it as already watched is still bugged.

**Comment by karnavara** [comment]
Nevermind , false alarm.

The first video worked and it was marked as watched when fully watching it manually - but now the next day it is broken again.

Both manually watching til the end and pressing the marked as watched are still bugged :(

**Comment by karnavara** [comment]
Someone with different reports ? Is it working for someone ?

**Comment by Section25** [comment]
For me, if a video runs all the way to the end; i.e. the window closes by itself (according to my preferences, 'Stop playback after one video'), the the thumbnail progress bar shows 100% but if I even stop one second before the end, it shows about 10%.

**Comment by karnavara** [comment]
> For me, if a video runs all the way to the end; i.e. the window closes by itself (according to my preferences, 'Stop playback after one video'), the the thumbnail progress bar shows 100% but if I even stop one second before the end, it shows about 10%.

hmm interesting , sometimes I even have that 10% with fully watched videos too though..

**Comment by Sarcas666** [comment]
No, same for me. It seemed to work for a moment, but not anymore. Op 19 feb 2026 om 15:13 heeft karnavara ***@***.***> het volgende geschreven:﻿karnavara left a comment (yuliskov/SmartTube#5111)
Someone with different reports ? Is it working for someone ?

**Comment by Getfree** [comment]
I'm on version 30.82 now and the problem is still there. Almost all my watched videos show a 10% red bar.

**Comment by karnavara** [comment]
> No, same for me. It seemed to work for a moment, but not anymore. Op 19 feb 2026 om 15:13 heeft karnavara ***@***.***> het volgende geschreven:﻿karnavara left a comment ([yuliskov/SmartTube#5111](https://github.com/yuliskov/SmartTube/issues/5111))
> Someone with different reports ? Is it working for someone ?
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

Yea can confirm this behaviour, had high hopes as it seemed to work at first but then degraded :(



> I'm on version 30.82 now and the problem is still there. Almost all my watched videos show a 10% red bar.

Yea so we are still at square one I guess :/

**Comment by filipe-maia** [comment]
I think this is fixed in the last version.

**Comment by karnavara** [comment]
oh this would be so wonderful, will test it thoroughly

**Comment by disconnect5852** [comment]
For me this happens since the last version

**Comment by harrydbarnes** [comment]
Yep, seeing this again

**Comment by yuliskov** [comment]
Could this be merged with #4994 ?

**Comment by karnavara** [comment]
> Yep, seeing this again

Oh noes... so far it works for me but seeing your comment scares me again - hopefully it wont appear again.. thought it is fixed at last :(

**Comment by timeandtrials** [comment]
This bug is still present

**Comment by karnavara** [comment]
And here we go again , appears in latest version again this is so frustrating...

**Comment by Sarcas666** [comment]
Can confirm. Op 20 aug 2026 om 14:33 heeft karnavara ***@***.***> het volgende geschreven:﻿karnavara left a comment (yuliskov/SmartTube#5111)
And here we go again , appears in latest version again this is so frustrating...

**Comment by yuliskov** [comment]
32.23 'work-in-progress' build
- playback and history fixes

Beta testing:
Downloader code: 857152
Direct link: https://github.com/yuliskov/SmartTube/releases/download/latest/SmartTube_beta_testing.apk

Stable testing:
Downloader code: 403642
Direct link: https://github.com/yuliskov/SmartTube/releases/download/latest/SmartTube_stable_testing.apk

**Comment by smikwily** [comment]
The stable testing version seems to be marking stuff as watched a lot better. It seems to be playing the last little portion of the video once or twice after the video completes. The repeat is maybe a second long? I think I had at least once where it played the repeated portion twice instead of just once.

**Comment by karnavara** [comment]
> 32.23 'work-in-progress' build
> 
>     * playback and history fixes
> 
> 
> Beta testing: Downloader code: 857152 Direct link: https://github.com/yuliskov/SmartTube/releases/download/latest/SmartTube_beta_testing.apk
> 
> Stable testing: Downloader code: 403642 Direct link: https://github.com/yuliskov/SmartTube/releases/download/latest/SmartTube_stable_testing.apk

thanks a lot , I will throw it on my nvshield and test it asap !

**Comment by ACR-Jeff** [comment]
**Closing as Duplicate** 

Please feel free to resubmit your issue if you believe it has not been appropriately dealt with. and tag this issue in the Additional Information section.
