### ISSUE TITLE
[SOLVED][BUG]: Play/Pause button doesn't work when comments are open

### ISSUE THREAD

**Issue by LoonyBeLuna** [yuliskov/SmartTube#5172]
### Checklist

- [x] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [x] This issue contains only one bug.

### Affected version

30.56

### Device Type

Smart TV/Box

### Affected Android

Firetv stick 4k 

### Steps to reproduce the bug

Open a video, open comments, try to click play or pause.

### Actual behavior

Nothing happens.

### Additional information

In my old smarttube version could I pause and play the video at anytime when I read the comments.
But now is it not working.
I checked all settings and can't find a option for it.
The open comments section seems to ignore the button input on my firetv remote control.

**Comment by ambergooch** [comment]
I came here to report the same issue. None of the playback controls work while the comments section is open. I recently updated to version 30.56 from version 29.83 and the issue was present there as well, but it worked previously.

**Comment by Nano0k** [comment]
Yep. Play/pause, RW & FF do not work while comments are open in newly installed 30.68 beta on Fire Stick, after working fine on 29.88 beta.

[edit] The P/P, REW & FF hard buttons also do not work in 30.68 when the UI/control bar is visible and the focus is on one of the top/bottom buttons. They do work when the focus is on the scrubber/progress bar. The hard buttons work in 29.88 no matter where the focus is.

Happy new year and thanks for all the hard work.

**Comment by Nano0k** [comment]
This bug was fixed for me with ver. 30.75. Hope for you too.

Thanks for the fix!

**Comment by ambergooch** [comment]
No change on 30.75 for me, unfortunately.

**Comment by LoonyBeLuna** [comment]
> This bug was fixed for me with ver. 30.75. Hope for you too.
> 
> Thanks for the fix!

On which device?
I'm on FireTV, version 30.75 nothing happens when I have the comments open and press the ⏯️ play/pause button.
Maybe some setting needs to be enabled?
Since we all had to reinstall because of the security issue.

**Comment by Nano0k** [comment]
> No change on 30.75 for me, unfortunately.

Ack!

> On which device? I'm on FireTV

A Fire Stick 4K from a couple years back on Fire OS 6.7.0.9. [And it did not need any setting changed on my part.] Weird.

**Comment by LoonyBeLuna** [comment]
> > No change on 30.75 for me, unfortunately.
> 
> Ack!
> 
> > On which device? I'm on FireTV
> 
> A Fire Stick 4K from a couple years back on Fire OS 6.7.0.9. [And it did not need any setting changed on my part.] Weird.

I'm sure my stick is also like 4 years old, from early corona years.
Did you reinstall the app after it got recently hacked?
A few weeks ago had we to install it again.

**Comment by Nano0k** [comment]
> Did you reinstall the app after it got recently hacked? A few weeks ago had we to install it again.

Yep. Installed 30.68 beta via Downloader app per the readme and then restored my saved settings from 29.88 beta. Did not delete 29.88 yet. New version can find backups from old save directory just fine. Then when ST said it found a new update, did that internally in ST and 30.75 fixed the issue for me. Wish I could tell you why. :/

**Comment by LoonyBeLuna** [comment]
> > Did you reinstall the app after it got recently hacked? A few weeks ago had we to install it again.
> 
> Yep. Installed 30.68 beta via Downloader app per the readme and then restored my saved settings from 29.88 beta. Did not delete 29.88 yet. New version can find backups from old save directory just fine. Then when ST said it found a new update, did that internally in ST and 30.75 fixed the issue for me. Wish I could tell you why. :/

I didn't knew I could load old a backup. So maybe was there something in your backup files?

**Comment by Nano0k** [comment]
>maybe was there something in your backup files?

Maybe… wish I had answers for you.

**Comment by gitttt54** [comment]
FYIO: I'm using 30.98 on a 4k firestick. when I play a video and open the comments, I am able to pause the video with the PAUSE key on the remote control. Also, I can play a pause video pressing the PLAY key (which is the same as PAUSE) with opened comments.

**Comment by yuliskov** [comment]
Should be fixed right now.

**Comment by LoonyBeLuna** [comment]
> Should be fixed right now.

SmartTube 30.98 on FireTV 4k, it still don't work.
I checked for updates but there is none.

**Comment by yuliskov** [comment]
@LoonyBeLuna check this section Setting/Player/Dev. options/ If the Disable notifications is enabled, uncheck it

**Comment by LoonyBeLuna** [comment]
> [@LoonyBeLuna](https://github.com/LoonyBeLuna) check this section Setting/Player/Dev. options/ If the Disable notifications is enabled, uncheck it

The first option there about AOSP firmware, yeah that solved it! I really would not think that this was connected to it 🙄.

Please make sure others see your comment as solution :) if you can highlight it. (I don't know GitHub well enough).

Thanks!
