### ISSUE TITLE
(Bug) Categories on Home are mixed up

### ISSUE THREAD

**Issue by who-is-matt** [yuliskov/SmartTube#79]
I'm pretty sure I've noticed this occurring in both Smart YouTube TV and SmartTube Next (currently the most recent version, Beta 6.8), running on a 2019 nVidia Shield Pro, though I can't currently replicate the issue in Smart YouTube TV.  The issue is itermittent but not uncommon when using SmartTube Next.  When browsing the Home screen, videos appear in one category that belong in the category row below it.  The videos in the first half of the row are correct, but the latter half should be in the next row down.  Reloading the Home screen (such as by navigating to the Gaming or Subscriptions page and then back) usually fixes the issue temporarily.

[**Edit**: It's not necessarily the immediate next row.  The problem happened again just now, with the last half of a category row populated by videos from a non-adjacent category row (and the latter half of that category row being populated by videos from yet another category row, and etc.).  However, it does seem to be consistent that the first half of the videos in a row are appropriate to the row, while the last half are being pulled from a different category row on the Home page.]

Note that in the attached screenshots, the selected category row is "Trailers", while the next category row is "Felicia Day".  The first few videos in the "Trailers" category are correct (as shown in the first screenshot), but as I scroll to the right (as shown in the second and third screenshot) the remaining videos in the row are being pulled from the "Felicia Day" category.  While it is not shown in the screenshots, the same is true of the next few rows, with the latter half of the "Felicia Day" category being populated by videos from the category row beneath it.
![Screenshot_20201102-220640](https://user-images.githubusercontent.com/4270243/97949661-f97dd400-1d59-11eb-971b-d21a279a9c0c.png)
![Screenshot_20201102-220648](https://user-images.githubusercontent.com/4270243/97949859-8f196380-1d5a-11eb-8499-e1bdc09c3d4c.png)
![Screenshot_20201102-220653](https://user-images.githubusercontent.com/4270243/97949870-96d90800-1d5a-11eb-83da-60bcf8aa34db.png)

**Comment by foreveryoungforty** [comment]
I think it's fixed in update 6.8

**Comment by ChipSkylark37** [comment]
Still happening as of the latest update 10.96.

**Comment by who-is-matt** [comment]
Still happening on latest update 12.53

![SmartTubeNext Beta_20210917_234747](https://user-images.githubusercontent.com/4270243/133873145-6a6d16a8-dc9c-498a-a268-5f339b2097e3.png)
